### ISSUE TITLE
Schedule calculation button in developer mode

### ISSUE THREAD

**Issue by rbhagat30** [afawcett/declarative-lookup-rollup-summaries#574] opened 2017-10-12 05:28 UTC
i am using calculation mode as 'developer'but can not get  the option to schedule calculate it i tried to schedule rollupsummary . i want to execute calculate button on daily basis  please help to schedule calculation on daily basis

**Comment by afawcett** [comment] 2017-11-25 19:47
Duplicate of https://github.com/afawcett/declarative-lookup-rollup-summaries/issues/572

**Closed by afawcett** 2017-11-25 19:47 UTC
