### ISSUE TITLE
Error Message "Invalid field 'CreatedDate' for object 'dlrs__LookupRollupSummary__c'" when creating an account happening

### ISSUE THREAD

**Issue by JesssicaHanna** [afawcett/declarative-lookup-rollup-summaries#432] opened 2016-11-18 01:14 UTC
Hi,

As the system Admin I am not receiving this error but my users are and I can't figure out why.

Review all error messages below to correct your data.
Apex trigger dlrs_AccountTrigger caused an unexpected exception, contact your administrator: dlrs_AccountTrigger: execution of AfterInsert caused by: dlrs.fflib_QueryFactory.InvalidFieldException: Invalid field 'CreatedDate' for object 'dlrs__LookupRollupSummary__c': (dlrs)

Any help would be much appreciated I don't want to turn off the rollups.

Jessie

**Comment by afawcett** [comment] 2016-12-05 01:07
Can you share a screenshot of your rollup definition please?

**Comment by JesssicaHanna** [comment] 2016-12-06 21:38
Hi

I was able to fix the issue by not having the "deploy code to support record merging" checked when deploying the child trigger. For me the weird part was that as the sys admin I could create account records but none of the other users code. So I am wondering if it has something to do more with a user setting when you deploy the additional code?

![image](https://cloud.githubusercontent.com/assets/23490273/20944572/d908d230-bbb8-11e6-9704-b02210d3dd24.png)

**Comment by afawcett** [comment] 2016-12-09 02:16
Hmmm most interesting, thanks for sharing, this sounds like a bug, i'll have a go at recreating it in a test org.

**Comment by jschneider-nexgen** [comment] 2017-04-11 01:51
I am receiving a similar error when creating an account.

Error message is
`dlrs_AccountTrigger: execution of AfterInsert caused by: System.SObjectException: Invalid field Parent for Account Class.dlrs.RollupService.handleRollups: line 842, column 1 Class.dlrs.RollupService.triggerHandler: line 302, column 1 Trigger.dlrs_AccountTrigger: line 7, column 1`

**Comment by afawcett** [comment] 2017-04-15 04:38
This is strange, while i am not sure why it allowed it, but Parent is not a valid relationship field, try ParentId instead. https://andyinthecloud.com/2014/05/08/account-hierarchy-rollups-clicksnotcode/

**Comment by JesssicaHanna** [comment] 2017-05-24 23:01
Hi,

I am still having issues with this error. I received this email when a user was trying to create a membership which pushes data to an account. Not sure if this is helpful at all.

Sandbox

Apex script unhandled trigger exception by user/organization: 0050j000000K8jG/00D0j000000CqSV Source organization: 00Do0000000J1uj (null)
dlrs_MembershipTrigger: execution of AfterInsert

caused by: dlrs.fflib_QueryFactory.InvalidFieldException: Invalid field 'CreatedDate' for object 'dlrs__LookupRollupSummary__c'

Class.dlrs.fflib_QueryFactory.getFieldToken: line 95, column 1
Class.dlrs.fflib_QueryFactory.addOrdering: line 446, column 1
Class.dlrs.fflib_SObjectSelector.configureQueryFactory: line 392, column 1
Class.dlrs.fflib_SObjectSelector.newQueryFactory: line 294, column 1
Class.dlrs.fflib_SObjectSelector.newQueryFactory: line 276, column 1
Class.dlrs.RollupSummariesSelector.CustomObjectSelector: line 161, column 1
Class.dlrs.RollupSummariesSelector: line 76, column 1
Class.dlrs.RollupService: line 992, column 1
Class.dlrs.RollupService: line 673, column 1
Class.dlrs.RollupService.triggerHandler: line 307, column 1
Trigger.dlrs_MembershipTrigger: line 7, column 1

**Comment by JesssicaHanna** [comment] 2017-05-25 20:22
Hi,
I feel like this is a user permission set because as the system admin I can create records without running into the above error but all of my users are running into this error. I can't for the life of me figure out what permission is needed on the users records so that this error will stop occurring.

Please Help,
Jessie

**Comment by afawcett** [comment] 2017-05-27 18:48
Yes it is most odd.... you should not have to... but... can you try assigning the rollup permission set to one of the users and trying again. Another issue posted here seems to have been resolved by doing this.

**Comment by afawcett** [comment] 2017-05-28 05:54
Here is the issue that seems to indicate adding permissions (the poster does not state which ones) https://github.com/afawcett/declarative-lookup-rollup-summaries/issues/285 solves it. I would go with the process permission set packaged with the tool as a test. I've spent the last half hour trying to repo this and i just cannot, can you confirm what version your on?

**Comment by JesssicaHanna** [comment] 2017-05-29 16:44
Hi,

That person no longer works at Pacific Science Center. I gave the profile access to all of the apex classes that start with dlrs. On the user permission set I gave the user both Lookup Rollup Summaries (Configure Rollups and Process Rollups). I also upgraded to version 2.8 to see if that would magically make the error go away. All of this is in sandbox, did not want to touch production even though it is also triggering the same error.


Thanks,

Jessie

Jessica Hanna | PACIFIC SCIENCE CENTER
Database Administrator | P (206) 269-2146 | jhanna@pacsci.org<mailto:jhanna@pacsci.org>
Pacific Science Center is an independent, not-for-profit institution that ignites curiosity and fuels a passion for discovery, experimentation, and critical thinking.
Terracotta Warriors of the First Emperor<https://www.pacificsciencecenter.org/terracotta-warriors/>
April 8 – September 4
Embark on a once-in-a-lifetime experience 2,200 years in the making.

**Comment by afawcett** [comment] 2017-05-29 18:10
Ok thats understood, did you try each change incrementally to see which resolved the issue? Any idea which one resolved it?

**Comment by JesssicaHanna** [comment] 2017-05-29 18:26
Hi,

I haven’t been able to resolve the issue. I’m not sure if I should try to uninstall the package from sandbox and then reinstall the package to see if a fresh start would help?

Thanks,

Jessie


Jessica Hanna | PACIFIC SCIENCE CENTER
Database Administrator | P (206) 269-2146 | jhanna@pacsci.org<mailto:jhanna@pacsci.org>
Pacific Science Center is an independent, not-for-profit institution that ignites curiosity and fuels a passion for discovery, experimentation, and critical thinking.
Terracotta Warriors of the First Emperor<https://www.pacificsciencecenter.org/terracotta-warriors/>
April 8 – September 4
Embark on a once-in-a-lifetime experience 2,200 years in the making.

**Comment by afawcett** [comment] 2017-05-30 02:56
@JesssicaHanna is it possible for you to grant subscriber access to me and provide me a list of steps?

**Comment by JesssicaHanna** [comment] 2017-05-30 18:06
Hi,

I have given you access to our sandbox (My profile that doesn’t error out and a co-worker’s profile that has the errors). Please let me know if you need anything else.

Below are the steps for us to create a membership with a screen shot.

Creating New DC & Corporate Membership that is complementary

1.       Click the Membership tab

2.       Click New button

3.       Enter Guest Name information

a.       EX. John doe

b.       If doing a corporate membership leave space blank

4.       Enter Account Name

a.       Corporate: enter company name EX. Microsoft

b.       Dc Membership:  enter household name EX. John Doe Household

5.       Enter SW Pass number

6.       Enter Membership Level

7.       Enter complimentary Membership date will be same as transaction date

8.       Click Complimentary Membership

9.       Fill in complimentary membership reason EX. Breakfast

10.   Enter Membership effective and expiration date

11.   Enter SW guest number

12.   Click save
[cid:image001.png@01D2D932.3E776550]


Thanks,

Jessie

Jessica Hanna | PACIFIC SCIENCE CENTER
Database Administrator | P (206) 269-2146 | jhanna@pacsci.org<mailto:jhanna@pacsci.org>
Pacific Science Center is an independent, not-for-profit institution that ignites curiosity and fuels a passion for discovery, experimentation, and critical thinking.
Terracotta Warriors of the First Emperor<https://www.pacificsciencecenter.org/terracotta-warriors/>
April 8 – September 4
Embark on a once-in-a-lifetime experience 2,200 years in the making.

**Comment by afawcett** [comment] 2017-06-02 04:56
Ok i think its the API restrictions on the package, i cannot see the setting for some reasons, i suspect its due to subscriber login context. Can you review this help article and try again... https://help.salesforce.com/articleView?id=editing_client_security_profile.htm&type=0

**Comment by JesssicaHanna** [comment] 2017-06-06 21:50
Hi,

It seems that SFDC removed the API access from installed packages in Summer ’16.

https://help.salesforce.com/articleView?id=000239703&type=1

So I don’t know what to do.

Thanks,

Jessie


Jessica Hanna | PACIFIC SCIENCE CENTER
Database Administrator | P (206) 269-2146 | jhanna@pacsci.org<mailto:jhanna@pacsci.org>
Pacific Science Center is an independent, not-for-profit institution that ignites curiosity and fuels a passion for discovery, experimentation, and critical thinking.
Terracotta Warriors of the First Emperor<https://www.pacificsciencecenter.org/terracotta-warriors/>
April 8 – September 4
Embark on a once-in-a-lifetime experience 2,200 years in the making.

**Comment by afawcett** [comment] 2017-06-10 07:42
Hmmm very interesting... @JesssicaHanna, i suggest raising a support ticket with Salesforce, it seems that they may have removed this feature from your org and left the default to off perhaps? I spent quite a while debugging it and its definitely returning no Apex Describe information in the managed package code for your non-admin user.  Which according to historic posts i found via google is a symptom of having API access disabled. Feel free to share this explanation to them.

**Comment by afawcett** [comment] 2017-11-25 20:29
@JesssicaHanna did you make any progress with Salesforce support on this? I'll close out this issue for now, but please, no worries if you want resume discussions, we can re-open here. 👍

**Closed by afawcett** 2017-11-25 20:29 UTC
Labels: discussion
