### ISSUE TITLE
Custom Metadata Type DLRS causes error when saving record.

### ISSUE THREAD

**Issue by mjhill86** [afawcett/declarative-lookup-rollup-summaries#330] opened 2016-04-12 15:23 UTC
I've been using the newest version of DLRS (2.3) in a Sandbox environment and most of the Custom Metadata types work great, but there are times when the Metadata DLRS does not work, and I need to revert to using the original Lookup Rollup Summaries tab. In this scenario, I need to rollup information from one record on an object to that record's parent (all custom fields). When using the Metadata DLRS, I receive an error upon saving the record: 
"Error:Apex trigger dlrs_NU_EventTrigger caused an unexpected exception, contact your administrator: dlrs_NU_EventTrigger: execution of AfterUpdate caused by: System.NullPointerException: Attempt to de-reference a null object: Class.dlrs.RollupService.updateMasterRollupsTrigger: line 894, column 1"

Here's an example:

Metadata DLRS:
When enabled, I get an error when trying to populate the Relationship field that the DLRS is referencing. 
![2016-04-12_08-22-33](https://cloud.githubusercontent.com/assets/13588559/14460002/33db98dc-0089-11e6-9f4b-07a0c3d49e86.png)

Lookup Rollup Summary:
When I setup the same DLRS under Lookup Rollup Summaries, and activate it, I am able to successfully update the record without an error. 

![2016-04-12_08-28-54](https://cloud.githubusercontent.com/assets/13588559/14460005/37c7ef0e-0089-11e6-8059-dac1f4217fa9.png)

The debug log for the error is here:

[Custom Metadata DLRS Debug Log.txt](https://github.com/afawcett/declarative-lookup-rollup-summaries/files/215313/Custom.Metadata.DLRS.Debug.Log.txt)

Any info you can provide about changes I can make to the Metadata record would be great, or maybe it's an issue that needs to be corrected in the package, but either way, thought it might be helpful for you to have the information to troubleshoot.

Thanks!
Mollie

**Comment by afawcett** [comment] 2016-04-13 20:50
When you use the Custom Metadata route, it creates 'shadow' records in the old Custom Object based rollups, the error your getting suggests these records have been deleted. Can you check what records you have in the original Lookup Rollup Summaries tab. 

BTW, the error your getting is this (as per your attached log), i don't see an error relating to populating the Relationship field, am i missing something?

08:35:03.64 (434978952)|FATAL_ERROR|System.NullPointerException: Attempt to de-reference a null object

Class.dlrs.RollupService.updateMasterRollupsTrigger: line 894, column 1
Class.dlrs.RollupService.handleRollups: line 777, column 1
Class.dlrs.RollupService.triggerHandler: line 307, column 1
Trigger.dlrs_NU_EventTrigger: line 7, column 1
08:35:03.64 (434997200)|FATAL_ERROR|System.NullPointerException: Attempt to de-reference a null object

**Comment by afawcett** [comment] 2016-06-12 09:31
@mjhill86 I do think there is some kind of issue here, so i'm going to make it a bug, even though we don't have a repo we can try to find one.

**Comment by afawcett** [comment] 2016-08-15 19:26
Ok, so this issue is a duplicate of one i've just fixed in v2.5, please upgrade to that version and try again. Thanks.

**Closed by afawcett** 2016-08-15 19:26 UTC
Labels: bug
