### ISSUE TITLE
DLRS should not edit/update a record when the recalc does not cause the value to change

### ISSUE THREAD

**Issue by JimBTek** [afawcett/declarative-lookup-rollup-summaries#370] opened 2016-08-09 16:34 UTC
It would be ideal if DLRS checked to see if the value changed when doing a manual or scheduled calculation. 

I see two routes (maybe there are more):
1. Track the last time the scheduled job was run and only calculate on records that have been modified since then
2. do all the calculations, but before updating records evaluate if the value changed or not and only update the records that need to be updated. 

I can see keeping the manual calculate button where it does a full calculate no matter what to clean up any issues someone might have, but the schedulable version might be nice to not have all my client's records updated hourly/daily/etc.

This is a minor annoyance but if you are using scheduled or manual calculations it changes the last modified date and user.  This could also perhaps help with the 50K limit? I don't recall if that limit is records that are queried vs. updated.

**Comment by afawcett** [comment] 2016-08-10 20:34
Hi Jim, 50k applies to records queried. I'm not sure how it will know what parent records to update or not without querying the child records. But i guess your saying it could only include records that have been inserted or updated since the last run? What about deleted records? I guess this could some how combine the use of the Replication API but this is not a query operation. Hmm....

**Comment by JimBTek** [comment] 2016-08-10 20:48
ah ok, yeah so you can't avoid querying them to see if they changed.

On the updating side I have seen some APIs check for ischanged since the
last timestamp the API ran, and I have seen ETL setups where after you calc
the results but before you do an update you compare your results to what is
in the record and only update if they don't match to reduce your number of
updates/batches.

current logic is:

- Have final list/set of calculated fields
- update records

future could be:

- Have final list/set of calculated fields
- Grab all the parent records where the update will take place on
- Loop/compare the values
- add to a new list/set if the values differ
- update records

This is certainly in the nice to have column, not a need to have.

Best,

Jim Bartek
BTek Ventures, LLC
317-292-6301
BTekVentures.com

**Comment by afawcett** [comment] 2016-08-10 20:51
Yep i think that will add some benefit, but will need an additional query on the parent records than is done currently. It will though avoid needless overhead of flows, workflows and triggers that are not comparing themselves for changes in relevant fields.

**Comment by afawcett** [comment] 2017-01-09 03:26
So @JimBTek this is getting closer to being worked on for sure, its priority in the priority list is moving up! ;-)

**Comment by JimBTek** [comment] 2017-01-09 14:33
Nice!  Let me know if/when I can help test this or any other new features.
I'm going to be adding some more nightly rollups to Accounts for a client
this week and next.

Best,

Jim Bartek
BTek Ventures, LLC
317-292-6301
BTekVentures.com

**Comment by dirksierd** [comment] 2017-06-19 09:57
I stumbled upon this issue after being confronted with lots of changed records during a nightly sync at my Salesforce-connected webapp.
Apparently all records are changed at night, and the https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/dome_get_updated.htm method is picking them all up.
The Salesforce-instance has a DLRS-job at night, so I suppose fixing this issue will also make the SObject Get Updated-API more reliable.

**Comment by afawcett** [comment] 2017-07-29 20:06
@dirksierd thats a very useful observation about this API! 👍

**Comment by afawcett** [comment] 2018-01-01 20:55
Closing this as its a dupe of https://github.com/afawcett/declarative-lookup-rollup-summaries/issues/547

**Closed by afawcett** 2018-01-01 20:55 UTC
Labels: enhancement, priority
