### ISSUE TITLE
Count rollup not updating in real time when child record deleted

### ISSUE THREAD

**Issue by JLC999** [afawcett/declarative-lookup-rollup-summaries#418] opened 2016-10-18 18:08 UTC
I have a count type rollup that does not seem to be updating when the child record is deleted.  I've tried using both Name and Id as the field to aggregate but in both cases the counter does not change in real time when the child record is deleted.  It does change however if I tell the rollup to manually calculate.

**Comment by JLC999** [comment] 2016-11-07 16:29
I was just wondering if you've had a chance to look at this, I'm not sure if it's a known issue or if there is somehow an issue with the way this particular rollup has been configured.

**Comment by afawcett** [comment] 2016-12-05 00:34
Sorry @JLC999, been a little busy since late October, moving home and continent... Are you using Process Builder or the generated Apex Trigger? If you can include a screenshot of your rollup and any relevant details of your parent and child objects (validation rules, triggers on them etc) that would be great. Thanks.

**Comment by JLC999** [comment] 2016-12-06 17:17
@afawcett No worries about the delay, I know how it an be.  It's an apex trigger based rollup as seen in the screenshot.
![rollup screenshot](https://cloud.githubusercontent.com/assets/13090694/20935516/43cdf086-bb9c-11e6-93f4-213c2532a8db.png)

- No triggers other than dlrs triggers on the parent or the child
- The parent object has one active validation rule but I don't think it would have an affect, it just prevents coaches from being created that are younger than 18
- There are a couple of workflows and process builders set up on the child object that mainly set the child object name, send emails, and populate a couple of fields unrelated to the rollup.

Let me know if you need any more details.

**Comment by wes1278** [comment] 2016-12-06 21:56
Everything seems like it should work to me.

Only thing I can think of is if your trigger somehow doesn't have the option run on delete.

**Comment by afawcett** [comment] 2016-12-09 02:19
Yeah good thought @wes1278.... @JLC999 can you click the Manage Child Trigger button and send a picture of that screen please.

**Comment by JLC999** [comment] 2016-12-09 16:29
![child trigger](https://cloud.githubusercontent.com/assets/13090694/21056206/ddff254c-bdf1-11e6-92c5-bd148cf5ef86.png)

It looks like it's set to operate on delete but maybe I'm wrong.

**Comment by afawcett** [comment] 2016-12-31 23:26
Hmmmmm that is odd, can you try changing the Calculation Sharing Mode to User?

**Comment by 4flinus** [comment] 2017-03-01 09:56
I'm having the exact same issue with the only difference is that I'm doing a SUM and not count rollup. It is working on delete when I delete a record of the lookup child object but this child object also has a master detail to another object and when deleting this master object, the recalculation is not being triggered. Any ideas?

**Comment by afawcett** [comment] 2017-03-08 22:43
@4flinus this is because triggers do not fire on cascade deletes on the platform, so dlrs is not aware of this. I think this is a duplicate of this.... https://github.com/afawcett/declarative-lookup-rollup-summaries/issues/257 ? @JLC999 could this be the cause of your issue?

**Comment by 4flinus** [comment] 2017-03-09 07:43
@afawcett Yes, I found this out a while after posting here. Solved it with a simple delete trigger on the master object doing a delete dml for all children. Thanks!

**Comment by afawcett** [comment] 2017-03-12 19:16
Cool, glad your sorted. I will close this issue as its a duplicate of 257. Thanks again.

**Closed by afawcett** 2017-03-12 19:16 UTC
Labels: discussion

**Comment by shambiri** [comment] 2021-02-04 16:44
Hi all,

I am running into the same error and am unsure how to add a delete trigger on the parent object

"Solved it with a simple delete trigger on the master object doing a delete dml for all children. Thanks!"

Can someone please help.

Thanks

**Comment by cnaccio** [comment] 2022-10-06 03:59
@shambiri see this comment for details on how to implement this solution: https://github.com/SFDO-Community/declarative-lookup-rollup-summaries/issues/257#issuecomment-220631110
