### ISSUE TITLE
Missing Fields in LookupRollupSummary__c

### ISSUE THREAD

**Issue by dhoechst** [afawcett/declarative-lookup-rollup-summaries#129] opened 2015-03-05 20:55 UTC
When trying to deploy this code using Ant to an org, I get errors about missing fields:

RollupSummaries: line 140, column 106: Variable does not exist: LookupRollupSummary__c.FieldToOrderBy__c (line 54, column 4)

RollupSummariesSelector: line 41, column 4: Variable does not exist: LookupRollupSummary__c.ConcatenateDelimiter__c (line 36, column 38)

classes/RollupSummariesSelector.cls -- Error: Variable does not exist: LookupRollupSummary__c.UniqueName__c (line 49, column 4)

I suspect you missed that object in a commit as the managed package installs just fine.

**Comment by afawcett** [comment] 2015-03-05 22:09
Thanks, this is a duplicate of issue [120](https://github.com/afawcett/declarative-lookup-rollup-summaries/issues/120).

**Closed by afawcett** 2015-03-05 22:09 UTC
