### ISSUE TITLE
Concatenate Text Fields

### ISSUE THREAD

**Issue by daveerickson** [afawcett/declarative-lookup-rollup-summaries#78] opened 2014-10-14 15:48 UTC
I would like to be able to rollup text fields. It would be helpful to be able to choose the delimiter as well, such as a punctuation value or newline.

**Comment by wes1278** [comment] 2015-02-05 15:47
Is this a duplicate of issue #76? 
https://github.com/afawcett/declarative-lookup-rollup-summaries/issues/76 Can we close this and track there instead?

Thanks

**Comment by daveerickson** [comment] 2015-02-05 16:51
Yes, I think this qualifies as a duplicate of #76 .

**Closed** 2015-02-07 17:32 UTC
Labels: enhancement
