### ISSUE TITLE
Unable to merge accounts when DLRS trigger is deployed

### ISSUE THREAD

**Issue by ohadios** [afawcett/declarative-lookup-rollup-summaries#70] opened 2014-09-19 18:37 UTC
When attempting to merge accounts, I receive the below error:

Apex trigger dlrs_AccountTrigger caused an unexpected exception, contact your administrator: dlrs_AccountTrigger: execution of AfterDelete caused by: System.DmlException: Update failed. First exception on row 0 with id 0016000000MK0a4AAD; first error: SELF_REFERENCE_FROM_TRIGGER, Object 0016000000MK0a4AAD is currently in a merge operation, therefore a trigger can not update it.: []: (dlrs)

**Comment by afawcett** [comment] 2016-06-19 09:24
This is a duplicate of issue https://github.com/afawcett/declarative-lookup-rollup-summaries/issues/303, which has now been fixed in v2.4.1. Closing this one.

**Closed by afawcett** 2016-06-19 09:24 UTC
Labels: bug
