### ISSUE TITLE
Unable to connect to the Salesforce Metadata API.

### ISSUE THREAD

**Issue by Bazza2015** [afawcett/declarative-lookup-rollup-summaries#110] opened 2015-01-23 11:04 UTC
Hi,

I am experiencing the same problems as reported in issue #102.

I've installed the package 1.16, also tried uninstalling and installed 1.15 but receive the same error message. Re-installed 1.16 and currently receive the error message:

Unable to connect to the Salesforce Metadata API.
A Remote Site Setting must be created in your org before you can use this tool.
Press the Create Remote Site Setting button to perform this step or refer to the post install step below to perform this manually.

Under Remote Sites, I have an entry for dlrs_mdapi setup as https://dlrs.eu0.visual.force.com

When trying to activate a summary, I receive the error message:
Error: Apex Trigger dlrs_AccountTrigger has not been deployed. Click Manage Child Trigger and try again.

Any ideas on why this is happening?

**Comment by afawcett** [comment] 2015-01-24 09:38
Yeah i remember issue 102, it was intermittent in the end, the poster gave me support access and i was able to deploy the trigger and didn't see any sign of the remote site issue, most odd. In your case, is it happening all the time, no matter how many times you try to deploy the trigger? If so, i'd love to take a closer look if you would be happy to arrange support access? I would just need to know your Org ID. If not, maybe some more screenshots and Apex Debug logs can help me get a closer look. Let me know, keen to get to the bottom of this for sure! :+1:

**Comment by Bazza2015** [comment] 2015-01-26 08:16
Hi Andrew,

Yes it happens every time, although I may have missed something completely obvious when deploying the managed package.

I’ve granted you access, org id = 00D200000005B5O

Best regards,
Barry

**Comment by afawcett** [comment] 2015-01-28 08:59
Sorry Barry, can you give me a little more time to go in, as i support this tool in my spare time i don't often get back to these issues within a day. Can you extend the support access a little further please and I'll take a look. Thanks. :+1:

**Comment by Bazza2015** [comment] 2015-01-28 09:02
No problem, access extended.

**Comment by afawcett** [comment] 2015-01-28 09:20
Ok, trigger deployed, i didn't see any issues on the tab splash page (suggesting the remote site doesn't exist), nor did i encounter any errors deploying the trigger. I did also briefly enable the Active checkbox on the trigger to check that, also good. So i've logged out, the trigger is deployed, but i have left the Active checkbox unchecked for you to enable later. Its all very strange this problem, this is exactly what happened in the other issue, as soon as i went in it was working! :+1:

**Comment by Bazza2015** [comment] 2015-01-28 09:25
Ok thanks for your help. How bizarre!
I see the error on the splash screen (attached) but I am now able to activate the trigger.
![screenshot](https://cloud.githubusercontent.com/assets/10668839/5935166/a98dc074-a6cf-11e4-8fbd-6dd7a54e27ff.JPG)

**Comment by afawcett** [comment] 2015-01-28 09:31
That is really spooky, considering how i logged in as your user, as mad as it might sound i am starting to wonder if logging in via Subscriber Support has some soothing effect on the issue?!?!?! Is there anything unusual about your user you can think?

**Comment by Bazza2015** [comment] 2015-01-28 09:37
I'm setup with the System Administrator profile. I've been administering the system for the past 7 years and not aware of any obvious limitations on this profile. I took on board the advise provided in issue #102 to no avail. Thought an install of an older version might fix but no joy.

**Comment by afawcett** [comment] 2015-01-28 10:03
Most odd, i'm going to leave this open as an enhancement, to log a bit more info on the above page when this issue occurs (internally its catching an error to determine if MD API is configured). Maybe exposing more info (at the cost of it looking a little more techie) might help in the future.

**Comment by Bazza2015** [comment] 2015-01-28 10:15
No problem.

**Comment by itsabsolute** [comment] 2015-01-28 11:41
Andrew, the issue 102 I logged still perists and is likely related. Very interested and this is on the radar, I can grant you access as well if that helps troubleshoot.

**Comment by afawcett** [comment] 2015-02-10 08:36
Ok, i've added some additional debug output to the page, this will be in the next release, likely this coming weekend. As you can see from the screenshot when a connection failure is found, it will dump the underlying exception text. The one i get is expected, since you both have the Remote Site setting setup, i'm assuming there is some other underlying error for which this new debug feature will reveal. It works btw regardless of subscriber support, so you can check it yourselves and pass back here. Hopefully this will shed some more light on the matter! :+1: 

![screen shot 2015-02-10 at 09 36 57](https://cloud.githubusercontent.com/assets/1167760/6123901/4c63aa9c-b108-11e4-8442-cda8d1d77863.png)

**Comment by Bazza2015** [comment] 2015-03-11 09:40
Hi Andrew,
I've deployed the latest code release and can now see the debug message on the splash screen. Still having problems deploying new rollups. Hopefully the below information can provide new insight into the issue.

When I try to activate a new rollup, I receive the following:
Error: Apex Trigger dlrs_CaseTrigger has not been deployed. Click Manage Child Trigger and try again.

When I click Manage Child Trigger I receive the following:
Error:
Salesforce Metadata API connection failure, click the link below to configure.

When I go to the spash screen and click Remote Site Setting: 
DEBUG USE ONLY: Web service callout failed: WebService returned a SOAP Fault: INVALID_SESSION_ID: Invalid Session ID found in SessionHeader: Illegal Session faultcode=sf:INVALID_SESSION_ID faultactor=

**Comment by afawcett** [comment] 2015-03-11 18:43
Hmmmmm can you check the 'API Access' setup against the package, go to Setup and Installed Packaged, click the package and check what 'API Access' says.... 

![screen shot 2015-03-11 at 18 45 17](https://cloud.githubusercontent.com/assets/1167760/6604163/8da9a2d6-c81e-11e4-8395-fbc9a3193f65.png)

**Comment by afawcett** [comment] 2015-03-11 18:44
You could also check that your profile has 'API Enabled' ticked.

**Comment by Bazza2015** [comment] 2015-03-12 08:46
API access unrestricted and API enabled on my profile.

[cid:image004.jpg@01D05CA1.36D9D540]

[cid:image003.png@01D05CA1.0A586680]

**Comment by afawcett** [comment] 2015-03-12 09:17
The images didn't make it through above, but i see your comment anyway, hmmm.... so.... Session ID's are not all made equal, things like the above and other factors can cause them to carry different capabilities when used, so i suspect something else in your environment is adjusting the Session Id for your user, i just cannot think what right now... Do you have things like community or my domain enabled perhaps?

**Comment by Bazza2015** [comment] 2015-03-12 14:18
I don’t have community or domain enabled.

I can de-activate / activate an existing rollup summary without any problems, e.g. Rollup Number of Child ActWS (this was the roll-up you were able to activate when you logged in remotely).
When I create a new rollup and try to activate I get Aprex trigger error message. Screenshot attached (Error: Apex Trigger dlrs_CaseTrigger has not been deployed. Click Manage Child Trigger and try again)

I’ve granted temporary access to see if you can activate remotely.

**Comment by afawcett** [comment] 2015-03-12 18:43
I can for sure help you out by deploying the trigger via Subscriber Support, once this is done for a child object, you can freely activate/deactive an existing or new rollup based on that child. Let me know which rollup you want me to press the Mange Child Trigger button on, and i'll help you through this while we try to figure this big puzzle out....

**Comment by Bazza2015** [comment] 2015-03-13 08:49
Thank you Andrew,

Could you activate “Closed Cases This Month” please?

**Comment by afawcett** [comment] 2015-03-13 18:10
Ah sorry, the subscriber login must have timed out, if you can extend over the weekend, i can try and do then for you.

**Comment by Bazza2015** [comment] 2015-03-16 08:37
No problem, I’ve extended it for another 7 days.

**Comment by afawcett** [comment] 2015-03-17 21:22
The trigger is now deployed, you can now toggle the Active field on the rollup or any other rollup based on that object.

**Comment by Bazza2015** [comment] 2015-03-18 12:00
Thanks for your help once again.

**Comment by afawcett** [comment] 2015-03-20 08:13
No problem, i'll keep this open, if your able to help when i get back to it, i'd like to keep digging on this one, not sure what the next step is yet, but if your game, i'd really appreciate access to someone who can repo the issue until i can. Thanks again for your patience.

**Comment by Bazza2015** [comment] 2015-03-20 09:44
Sure not a problem, drop me a mail if you want to do some testing.

**Comment by itsabsolute** [comment] 2015-11-04 21:38
Hi Andrew, I am still having the same issues with this and cannot seem to use the tool. I am on the latest version 1.24 and get the following error: Web service callout failed: WebService returned a SOAP Fault: INVALID_SESSION_ID: Invalid Session ID found in SessionHeader: Illegal Session faultcode=sf:INVALID_SESSION_ID faultactor=

Any ideas?

**Comment by afawcett** [comment] 2015-11-29 09:46
Hi, i'm honestly at a bit of a loss as to whats causing this. I see when we last looked at this over on issue 102, i logged in and it worked for me. As I recall you are trying as your Admin user as well, right? Only other thing i am wondering is the API Settings on the package itself. Go to Installed Packages, click the details of the DLRS package and check what it says for API Security.

**Comment by anilakhwaja** [comment] 2016-02-25 21:17
Hi Andrew,

I am facing the same issue where it says following

> DEBUG USE ONLY: Web service callout failed: WebService returned a SOAP Fault: INVALID_SESSION_ID: Invalid Session ID found in SessionHeader: Illegal Session faultcode=sf:INVALID_SESSION_ID faultactor=

I have checked that I have API Enabled on my profile and API Access for package is Unrestricted.

I have domain and communities enabled in my organization.

Please let me know, what can be the issue.

Thanks
Anila

**Comment by afawcett** [comment] 2016-02-29 18:28
Are you using the tool within Lightning Experience or something other than Salesforce Classic UI?

**Comment by anilakhwaja** [comment] 2016-02-29 18:34
No, we have not enable lightning in our environment.

**Comment by afawcett** [comment] 2016-02-29 18:46
Does this problem occur all the time? Have you tried with an Admin user?

**Comment by anilakhwaja** [comment] 2016-02-29 18:52
I am trying it with system admin user. I haven't yet tried it with any other profile.

**Comment by afawcett** [comment] 2016-02-29 19:13
I'm honestly at a bit of a loss, Salesforce do modify the Session Id capabilities usually its due to the profile and/or package API attributes or more recently being in a Lightning Component, neither of these are your case. I will try to enable domain and community in one of my test orgs and see if that has an impact, though if it does i'm not really sure what to do about it in the tools current form. One option here would be to have a separate authentication flow for the tool itself but thats quite a bit of work to introduce.

**Comment by afawcett** [comment] 2016-02-29 19:15
Ok wondering something.... if the metadata API callout URL is not correctly calculated if my domain is enabled, can you enable the debug log and share here please?

**Comment by anilakhwaja** [comment] 2016-02-29 19:20
Let me try that, I'll update you soon

**Comment by afawcett** [comment] 2016-02-29 19:24
Ok i've enabled My Domain and its still working for me.... looking into communities now...

**Comment by afawcett** [comment] 2016-02-29 19:27
Ok created a community in my test org and its still working fine... :+1:

**Comment by afawcett** [comment] 2016-02-29 19:29
If you want to enable Subscriber Support access and let me know your Org ID i can have a quick look, see if anything looks odd in the debug logs i get (which are more extended with the DLRS code).

**Comment by anilakhwaja** [comment] 2016-02-29 19:31
we have installed managed application and therefore I am unable to see the log. I have given you the subscriber access to my org. My Org Id is 00D11000000Degr

**Comment by afawcett** [comment] 2016-02-29 19:36
I don't see any user listed for me to login as, when i bring up the subscriber support page for this org, can you double check you've enabled the user please.

**Comment by anilakhwaja** [comment] 2016-02-29 19:40
Please try again.

**Comment by afawcett** [comment] 2016-02-29 20:14
Still not showing. Its the Sandbox yes? Can you check the Org ID you've given me please.

**Comment by anilakhwaja** [comment] 2016-02-29 20:22
Sorry, the Org Id is 00Dj0000000IiYy and it is a production system

**Comment by anilakhwaja** [comment] 2016-03-02 15:28
Hi Andrew,
Can you access the org?

**Comment by afawcett** [comment] 2016-03-04 19:04
Logged in, with both users and the Manage Child Triggers page does not report any errors. I also see that you have an active Rollup, which suggests things have been working for someone. I cannot reproduce the problem through subscriber support sorry. It has been observed before that this problem does not show up when using Subscriber Support, most frustrating i know.

**Comment by pbatf4** [comment] 2016-03-16 15:30
I just ran across the same issue. I noticed another Administrator had changed the session settings and Checked the "Lock sessions to the IP address from which they originated" setting.

I unchecked this, logged out and back in and the error went away. I also checked it again, logged out and back in and the error returned.

Here is the setting:
![image](https://cloud.githubusercontent.com/assets/4895509/13817928/70b97ec4-eb6a-11e5-8200-bf585aa59d22.png)

**Comment by anilakhwaja** [comment] 2016-03-16 19:20
Thanks, it worked.

**Comment by afawcett** [comment] 2016-03-16 20:17
Wow what a discovery, this makes perfect sense now! Thanks so much for this, i'm going to put this in the known issues list.

**Comment by afawcett** [comment] 2016-06-15 19:18
I added this to the known issues list.

**Closed by afawcett** 2016-06-15 19:18 UTC
Labels: bug

**Comment by rbhagat30** [comment] 2017-09-27 12:43
can someone please suggest  how developer mode will work . i dont want to schedule job on real time in need to select developer mode. but i need to click on calculate button  manully to get the result . when i am trying to schedule job to excute schedule button it is not allowing me to use objects of this pacakge

**Comment by LanCRM** [comment] 2018-06-18 14:00
Hi Andy,
I'm having this problem now, but I think it's because this org has restricted IPs.
Remote Site setting is configured.

DEBUG CODE:
Web service callout failed: WebService returned a SOAP Fault: INVALID_SESSION_ID: Invalid Session ID found in SessionHeader: Illegal Session faultcode=sf:INVALID_SESSION_ID faultactor=

Screen Shot of Managed Package settings doesn't have any line for API connection!  (hope it comes through).

<img width="1121" alt="screen shot 2018-06-18 at 9 56 46 am" src="https://user-images.githubusercontent.com/37852685/41540428-40490b58-72de-11e8-940e-cdd43210a155.png">

Do you have any ideas?  Of all my customers, this is the only one that has given me a problem and I think it's their security settings...

Thanks!
Leigh-Anne

**Comment by DanDonin** [comment] 2018-06-18 14:13
Just deploy the trigger via changesets as the metadata API is only used for
that magic

**Comment by LanCRM** [comment] 2018-06-18 14:21
Just deploy the trigger via changesets?  
Forgive my confusion, I can't seem to get the Packaged installed properly let alone create a trigger.  
Are you referring to the APEX that's included in the package?  Is there one in particular I should be looking at?  They all seem to be active.

**Comment by DanDonin** [comment] 2018-06-18 14:29
The package seems to be installed from your screenshot. If you are talking
about the message you get when you click in to create a dlrs you should be
able to bypass that screen with a button in the bottom right.

**Comment by LanCRM** [comment] 2018-06-18 14:46
This is what I see on my Welcome Page.  
I was able to set up the remote settings.  But it seems to be an issue with connecting with the API.  I saw some previous posts to check the API setting in the Managed Page page, but I don't even have a line there to say if it's Unrestricted or not.

<img width="1435" alt="screen shot 2018-06-18 at 10 45 18 am" src="https://user-images.githubusercontent.com/37852685/41543430-c2af7662-72e4-11e8-8b61-482b4b22c67c.png">

**Comment by DanDonin** [comment] 2018-06-18 15:02
Just click one tab over to the right :)

**Comment by LanCRM** [comment] 2018-06-18 15:04
:(  Salesforce Metadata API connection failure.  Never had this before.

<img width="1438" alt="screen shot 2018-06-18 at 11 03 16 am" src="https://user-images.githubusercontent.com/37852685/41544656-40459ca8-72e7-11e8-9e8e-83cd6ee3d46f.png">

**Comment by DanDonin** [comment] 2018-06-18 15:06
Use the classic non metadata based style?

**Comment by LanCRM** [comment] 2018-06-18 15:38
You mean like this?

<img width="1434" alt="screen shot 2018-06-18 at 11 37 39 am" src="https://user-images.githubusercontent.com/37852685/41546594-0d0eb842-72ec-11e8-81f8-f05b212cb392.png">
<img width="1403" alt="screen shot 2018-06-18 at 11 37 31 am" src="https://user-images.githubusercontent.com/37852685/41546595-0d35764e-72ec-11e8-8912-670046d737e2.png">

**Comment by LanCRM** [comment] 2018-06-18 15:38
I clicked Classic and will give it a try!  Stand by!

**Comment by LanCRM** [comment] 2018-06-18 15:52
OK - Stuck.
When I get to Manage Child Trigger, I get this error.  How would I deploy this dlrs_ContentDocumentTrigger as a changeset?

<img width="781" alt="screen shot 2018-06-18 at 11 41 45 am" src="https://user-images.githubusercontent.com/37852685/41546842-b250dccc-72ec-11e8-92fb-43aaeeb25f2b.png">

**Comment by DanDonin** [comment] 2018-06-18 15:54
Copy the apex and make your own trigger and your own test class

**Comment by LanCRM** [comment] 2018-06-18 15:55
I can't even view the APEX.  Thats the page I see when I click Manage Child Error.
I can't find the Trigger anywhere.

**Comment by LanCRM** [comment] 2018-06-21 00:01
@EmilyPagua no work around as yet.  In another org, a few of my roll ups caused some errors.  So I've been troubleshooting that too.

**Comment by afawcett** [comment] 2018-06-24 05:34
When you click Return to Welcome page can you show the screenshot?

**Comment by afawcett** [comment] 2018-06-24 05:37
Check the known issues in the README, there is some good tips on session issues. See screenshot above from the Welcome page, this shows a session error.

**Comment by EmilyPagua** [comment] 2018-06-25 18:18
@afawcett  this is the error, i did the steps shown in previous comments, but i still get the same error. 
![1](https://user-images.githubusercontent.com/2520686/41867858-483ffe4e-7882-11e8-9adc-cdce2294f6c4.png)

**Comment by bblcastro** [comment] 2018-07-30 16:06
@afawcett - I saw this post and I am experiencing the same issue. Can you help me?

**Comment by dlisovsky** [comment] 2018-10-18 17:41
@afawcett - the same issue(

**Comment by tlepke** [comment] 2020-12-16 20:24
Hi All, 

I am getting the same error: 

Nothing I have tried is fixing this. Thanks for the help!

![image](https://user-images.githubusercontent.com/71093926/102402469-0705bb00-3fa2-11eb-8284-8f8bde5a7026.png)
