### ISSUE TITLE
Increase Test Code length

### ISSUE THREAD

**Issue by jrz** [afawcett/declarative-lookup-rollup-summaries#455] opened 2017-01-30 10:00 UTC
The li,it of 255 is too small for any meaningful test.
If you have a couple of required fields, you're out of luck.

**Comment by jonlarosa** [comment] 2017-02-13 15:37
This is happening to other users too:

https://success.salesforce.com/_ui/core/chatter/groups/GroupProfilePage?g=0F9300000009O5pCAE&fId=0D53A00002xFndrSAC

https://success.salesforce.com/_ui/core/chatter/groups/GroupProfilePage?g=0F9300000009O5pCAE&fId=0D53A00002sFSn8SAG

**Comment by afawcett** [comment] 2017-02-18 22:05
This is a duplicate of this https://github.com/afawcett/declarative-lookup-rollup-summaries/issues/304 enhancement. I have been waiting for platform support in custom metadata for large text fields, this seems to have arrived now! So i'll progress the enhancement. Thanks!

**Closed by afawcett** 2017-02-18 22:05 UTC
