### ISSUE TITLE
Cannot Install dlrs trigger with merging enabled

### ISSUE THREAD

**Issue by alexandershively** [afawcett/declarative-lookup-rollup-summaries#811] opened 2019-04-09 21:41 UTC
I'm trying to install a dlrs trigger in a way that will allow contact record merging. Parent object is Contact. Child object is Campaign Member. I had the trigger installed without selecting the option for Deploy code to support record merging. However, this does not work because when this is installed, I get this error when trying to merge contacts: Apex trigger_ContactTrigger caused an unexpected exception, contact your administrator: dlrs_ContactTrigger: execution of AfterDelete caused by: System.NullPointerException: Attempt to de-reference a null object: (dlrs)

The issue we have is we cannot install the trigger with merging enabled because we have trigger management. Because we have trigger management we have to use the custom test method override. When you use the custom test method override, it only implements that on the child trigger. When you enable merging, a trigger on the parent (in this case, Contact) is also automatically created where without merging, a child trigger is only created. But when you go to deploy that trigger with merging enabled, you'll note that the test override only exists on the child trigger not the parent and the deployment fails because the test method override should apply to both triggers.

![DLSR](https://user-images.githubusercontent.com/16843412/55837213-940e2680-5ad5-11e9-9e05-870bde7e3dbd.png)

**Comment by afawcett** [comment] 2019-12-28 06:29
@alexandershively indeed it is an enhancement request to allow the generated paraent test code to be overriden. This maybe a dupe of that issue, but until I find it I will leave this one open. 👍

**Comment by AlexKasper** [comment] 2020-01-04 14:34
Just ran into this issue as well

**Comment by afawcett** [comment] 2020-04-06 23:17
@AlexKasper @alexandershively this enhancement has now been made in v2.12

**Closed by afawcett** 2020-04-06 23:17 UTC
Labels: enhancement
