### ISSUE TITLE
System.NoAccessException: Entity is not api accessible

### ISSUE THREAD

**Issue by jrshor** [afawcett/declarative-lookup-rollup-summaries#429] opened 2016-11-15 16:54 UTC
I get a Developer Script Exception email every hour or so from a sandbox where Declarative Lookup Rollup Summaries is installed. A screenshot of the error is attached. Has anyone seen this before?
![screen shot 2016-11-15 at 11 52 43 am](https://cloud.githubusercontent.com/assets/23482501/20315024/4d9196cc-ab2a-11e6-8f4d-4415a004cfed.png)

**Comment by StephanieKing** [comment] 2016-11-28 14:23
I am getting this error repeatedly from multiple orgs where I am using the App:

Apex script unhandled trigger exception by user/organization: 0051200000677wk/00DA0000000BkLF

dlrs_AccountTrigger: execution of AfterUpdate

caused by: System.NoAccessException: Entity is not api accessible

Class.dlrs.fflib_SObjectSelector: line 36, column 1
Class.dlrs.RollupSummariesSelector.CustomObjectSelector.<init>: line 102, column 1
Class.dlrs.RollupSummariesSelector.<init>: line 43, column 1
Class.dlrs.RollupService.describeRollups: line 992, column 1
Class.dlrs.RollupService.handleRollups: line 673, column 1
Class.dlrs.RollupService.triggerHandler: line 307, column 1
Trigger.dlrs_AccountTrigger: line 7, column 1

-----
Apex script unhandled trigger exception by user/organization: 00534000008cg7b/00D80000000M2V6

dlrs_AccountTrigger: execution of AfterUpdate

caused by: System.NoAccessException: Entity is not api accessible

Class.dlrs.fflib_SObjectSelector: line 36, column 1
Class.dlrs.RollupSummariesSelector.CustomObjectSelector.<init>: line 102, column 1
Class.dlrs.RollupSummariesSelector.<init>: line 43, column 1
Class.dlrs.RollupService.describeRollups: line 992, column 1
Class.dlrs.RollupService.handleRollups: line 673, column 1
Class.dlrs.RollupService.triggerHandler: line 307, column 1
Trigger.dlrs_AccountTrigger: line 7, column 1

-----
Apex script unhandled trigger exception by user/organization: 005j000000BvWLz/00Dj0000001pS6d

dlrs_ContactTrigger: execution of AfterUpdate

caused by: System.NoAccessException: Entity is not api accessible

Class.dlrs.fflib_SObjectSelector: line 36, column 1
Class.dlrs.RollupSummariesSelector.CustomObjectSelector.<init>: line 102, column 1
Class.dlrs.RollupSummariesSelector.<init>: line 43, column 1
Class.dlrs.RollupService.describeRollups: line 943, column 1
Class.dlrs.RollupService.handleRollups: line 635, column 1
Class.dlrs.RollupService.triggerHandler: line 307, column 1
Trigger.dlrs_ContactTrigger: line 7, column 1

**Comment by afawcett** [comment] 2016-12-05 00:58
@StephanieKing  and @jrshor have you seen the comments from @cdcarter in this [issue](https://github.com/afawcett/declarative-lookup-rollup-summaries/issues/426).

**Comment by afawcett** [comment] 2017-01-01 03:53
Closing this, as its a duplicate of another issue. Look for updates on https://github.com/afawcett/declarative-lookup-rollup-summaries/issues/360.

**Closed by afawcett** 2017-01-01 03:53 UTC
Labels: bug, duplicate, priority
