### ISSUE TITLE
Script exception error when deleting child record (NPSP)

### ISSUE THREAD

**Issue by kvonachen** [afawcett/declarative-lookup-rollup-summaries#246] opened 2015-09-10 15:56 UTC
I have several lookup rollup summaries created and when the user tries to delete or merge records (child records), I am getting a developer script exception error and the user is unable to perform the delete/merge process.  How can I keep the rollup active and avoid this error from happening?

**Comment by afawcett** [comment] 2015-09-12 09:25
Merging causes all manor of updates to fire and it can get complicated fast if you have many things going off. If you are you able to describe to me how to reproduce this problem with minimal rollup summaries (say by reproducing the issue in a fresh org from developer.salesforce.com) i can take a better look? Failing that if you give me the error thats appearing i might be able to speculate further as to what the next steps might be.

**Comment by kvonachen** [comment] 2015-09-22 17:58
Sorry for delay. It just happened again.  Here's the error message being received -- 

Validation Errors While Saving Record(s)
There were custom validation error(s) encountered while saving the affected record(s). The first validation error encountered was "Apex trigger dlrs_ContactTrigger caused an unexpected exception, contact your administrator: dlrs_ContactTrigger: execution of AfterDelete caused by: System.DmlException: Update failed. First exception on row 0 with id a0VA0000007mMTkMAM; first error: ENTITY_IS_DELETED, entity is deleted: []: (dlrs)". 


I'm tempted to add a filter to the rollup to ignore where IS_Deleted = TRUE. Thoughts?

**Comment by kvonachen** [comment] 2015-10-14 14:02
Andrew - any update on this?  The client is antsy to get this resolved and I'd love to know how to avoid this in the future.  Thanks!

**Comment by aheber** [comment] 2015-10-14 14:13
@kvonachen Can you provide specific replication details? 
Can you setup a roll-up in a clean org and reproduce the problem?

Just by looking at the error it appears that the error is coming after deleting a Contact record but the ID referenced isn't a contact ID -- At least not in most orgs -- I'm going to guess it is a custom lookup object that you're rolling the data up to.

I'm guessing that the roll-up is trying to update the parent/target object because the child was deleted, but the parent/target object was deleted as part of the merge. Could you confirm, and maybe give some additional insight to this process?

Are you using a tool to perform the merging?
Can you provide specifics regarding the object relationships?

Sorry for all the questions. It is critical that the problem is understood before it can be diagnosed and fixed.

**Comment by kvonachen** [comment] 2015-10-14 14:39
It seems this has to do with the Non-Profit starter package. We have Households, Accounts and Contacts.  When a duplicate contact is in an Account and you go to merge it, even though we're keeping the Household record, the rollup is failing -- the parent of the rollup is Household and the child is Contact.  The rollup is just supposed to populate the Household with a value, so I'm not sure why merging contacts would cause this error.  We are going to research the non-profit starter pack to see if others have had similar issues but any insight you can provide would be helpful!

**Comment by aheber** [comment] 2015-10-14 14:58
@kvonachen Thanks for the info, that helps a lot!

Could you provide a screenshot of your roll-up so I can try and replicate it? Should be easily replicated from what you're describing.

Thanks

**Comment by kvonachen** [comment] 2015-10-14 15:27
Sure thing!  
![image](https://cloud.githubusercontent.com/assets/5272536/10488400/7e86ab76-7266-11e5-96e6-6c0218df44ad.png)

**Comment by kvonachen** [comment] 2015-10-19 14:57
Any update on this?  One other option I'm considering is having this run as a scheduled job instead of RealTime.  Do you think that would resolve the issue?

**Comment by afawcett** [comment] 2015-11-29 10:12
Looking at your screenshot, i see that the Account object is not featured? Can you confirm the steps to reproduce please.

**Comment by afawcett** [comment] 2016-02-19 21:44
Not sure if this is still an issue or not? If so, @aheber or myself can try to continue to help.

**Comment by ashimasaigal** [comment] 2016-03-16 17:13
Hi @afawcett  and @aheber, I know this is closed, but I'm working with someone who is running into this exact same problem. They have a custom object (vouchers) that is off of Case. 

Case has a roll up of all the vouchers
Account has a roll up of that field on Case but with a filter criteria of Date__c = THIS MONTH

So, this error occurs when they attempt to move a contact from one Account to another. They are using the Nonprofit Starter Pack to manage the moving (there is special functionality to do the work: https://powerofus.force.com/articles/Resource/NPSP-Merge-or-Split-Households

I'm sure that what is happening is what you've already described above. First, has this been resolved elsewhere? And if not, what can I do to help you figure out what is happening?

Peace,

Ashima

**Comment by ashimasaigal** [comment] 2016-03-17 16:18
By the way, they have turned off real time and have set it up to be scheduled. This is not ideal, but at least everything is working. So, again, any suggestions or what can I get you so you can see what is happening. I'll do whatever I can to help.

**Comment by afawcett** [comment] 2016-03-20 10:37
No worries, i now have access to an org with NPSP installed and DLRS, so can try to reproduce this. Have you got a screenshot of your rollup definition?

**Comment by mnorthrup** [comment] 2016-03-21 20:21
![declarative rollup on account](https://cloud.githubusercontent.com/assets/16826931/13932910/dc864bcc-ef80-11e5-9c92-86200bb5f1ac.JPG)

**Comment by ashimasaigal** [comment] 2016-03-21 20:49
@afawcett, meet @mnorthrup , she's the client that is working on this issue. She can better respond to your request than I am able. I'll stay on the thread, in case, but please keep up with her. @mnorthrup , you might want to show him your voucher roll up as well as it could be the voucher that is causing the error.

**Comment by kvonachen** [comment] 2016-03-21 20:55
I'm having a very similar issue with a client of mine who is also on the 
NFP starter pack, and I've investigated the issue and it seems to stem 
from the Household structure of the package.   Here's a screenshot of 
one of the DLRS setups that is causing us issues.


They cannot use the NFP Contact Merge feature with any lookup rollups 
activated that are parent or child of Contact.  And when they use the 
standard Contact merge (from an Account record) they also run into 
problems (until we deactivate the rollup, which is not ideal!)

Kendra Von Achen  |  Managing Solutions Consultant
Fortimize  |  Fortify and optimize your business for growth.
m 973.876.3729  |  800.IMPLEMENT (800.467.5363) ext. 304




This email (including any attachments) is solely for the use of its 
intended recipient(s) and may contain information that is privileged, 
confidential, and exempt from disclosure under applicable law. Any 
unauthorized use, distribution, or disclosure is strictly prohibited. If 
you have received this message in error, please notify the sender 
immediately and delete the original email.



------ Original Message ------

**Comment by afawcett** [comment] 2016-03-22 21:34
I have setup this a tag to group [NPSP](https://github.com/afawcett/declarative-lookup-rollup-summaries/labels/NPSP) related issues.  

So we can see if we can team up on what i think is a general issue. My personal challenge is i don't have any knowledge of NPSP.  @JodiNA over in issue https://github.com/afawcett/declarative-lookup-rollup-summaries/issues/39 has kindly worked with to setup a reproduction org with DLRS and NPSP installed within. 

This has already led to one issue being resolved in v2.3 lets see if we can close in on more. I'm happy to create users in this org so we can work to reproduce the issues in that org and i can debug more easily, just message me via SF Community or DM via Twitter your email and i'll setup a user.

**Comment by ashimasaigal** [comment] 2016-03-23 18:36
@mnorthrup, can you help Andrew recreate the error in his production instance? He's already solved one bug, perhaps he can get that done too. Just message him your email address so he can set up a user for you, okay? If you cannot, let me know and I'll work with him on this.

**Comment by mnorthrup** [comment] 2016-03-23 23:25
I am unable to help until the middle of next week, as I am on vacation and have limited access to wifi. If it can wait until then, my email is mnorthrup@benziebacn.org.

________________________________

**Comment by afawcett** [comment] 2016-08-15 19:37
See comment [here](https://github.com/afawcett/declarative-lookup-rollup-summaries/issues/39#issuecomment-239904712).

**Closed by afawcett** 2016-08-15 19:37 UTC
Labels: discussion, NPSP, priority
