### ISSUE TITLE
Validation Errors 'ENTITY_IS_DELETED' While Saving when Parent gets Deleted As Well

### ISSUE THREAD

**Issue by sforcegarrett** [afawcett/declarative-lookup-rollup-summaries#39] opened 2014-06-03 19:52 UTC
The non-profit starter pack relates Contacts(child) to Households(parent and custom object).  When a single Contact is related to a single Household and one tries to delete the child contact the attached error is displayed.
![roll up error](https://cloud.githubusercontent.com/assets/7527447/3165777/ad989294-eb58-11e3-8425-273e899bc4c9.png)

I believe what is occurring is the Declarative Roll Up code is trying to update the parent with a roll up number while the non-profit starter code is trying to delete it and a conflict occurs.  Accounting for this issue may be an enhancement to this package but I thought I would offer this scenario.  How can we properly account for ignoring the roll up count if the parent is being deleted programmatically when the child is deleted?

I am happy to provide login access to review this scenario if needs be.  I seem to only be able to reproduce this in production at the moment.

**Comment by JodiNA** [comment] 2015-08-18 14:38
Hi all,

I'm actually experiencing this same issue in my sandbox, but not in production!  It's a new sandbox, and so there shouldn't be anything different than production.  Any suggestions?

Thanks!
Jodi

![apex_error](https://cloud.githubusercontent.com/assets/8515331/9332926/1e05401c-4595-11e5-9075-0a970af93189.jpg)

**Comment by JodiNA** [comment] 2015-08-18 14:43
Strike that, it is also giving me issues in production.  So it's not sandbox/production related.  I'm also using NPSP.

**Comment by afawcett** [comment] 2015-08-27 07:20
Hi this is an old and complex issue, not sure i ever did get round to debugging it looking at the trial, just in case though can you confirm your on the latest version of the tool?

**Comment by JodiNA** [comment] 2015-08-31 17:50
I'm using version 1.10.  Thanks!

This particular instance of this issue for us may become mute soon, because we are about to upgrade to NPSP 3.0 and will be able to use a native roll-up summary field instead of the lookup tool.  However, given that NPSP is managed and I can't see or modify any of the triggers, I'm guessing this issue will arise again with a different lookup.

**Comment by afawcett** [comment] 2015-08-31 20:40
Ok, let me know, as your on quite an old version of the tool, it would be good to upgrade before retrying.

**Comment by JodiNA** [comment] 2015-09-02 16:50
Oye, yes.  I didn't realize how behind I had gotten!  I will do that and repost if I'm still having the issue!

**Comment by JodiNA** [comment] 2015-09-02 17:27
Here I am again.  Now running 1.23 and still having the issue. :-(

**Comment by afawcett** [comment] 2015-09-12 09:32
Ok. I'm heading out to DF next week, but have marked this issue as a priority for the next major chunk of time i get to look at this. I note that i did reproduce it earlier in this discussion. There does however seem to be a theme around the NPSP, i do wonder if we need to pool resources and setup a shared org to demo setup and/or reproduce issues in, just a thought.

**Comment by afawcett** [comment] 2015-11-29 13:03
@JodiNA would you be able to help this issue and others around NPSP by setting up a free Developer Edition org with a repo of this issue?

**Comment by JodiNA** [comment] 2015-11-30 16:31
Hi Andy, I'm working on it.  I have to install NPSP into the dev org...  Thanks for looking into this further!

**Comment by afawcett** [comment] 2015-12-01 20:25
You should be able to install it into a dev org just like in production or sandbox? What issue are you having?

**Comment by afawcett** [comment] 2015-12-01 20:26
Lets try with an org with NPSP 2 in it first, we can always upgrade in due course or create another org for NPSP 3.

**Comment by JodiNA** [comment] 2015-12-01 20:33
When I give my dev. org credentials when trying to install, it's giving me an error that I entered invalid credentials.  I selected "install in sandbox" - perhaps that's not correct?

**Comment by JodiNA** [comment] 2015-12-11 18:03
Update - haven't had a chance to look into this further this week.  Will try again early next week!  (Dec. 14)

**Comment by afawcett** [comment] 2015-12-11 19:07
Ok thanks for the update. Looking forward to having this org available to the tools testing and repos. Thanks for putting the effort in to support this! :+1:

**Comment by afawcett** [comment] 2016-01-10 10:17
Hi @JodiNA hows the org coming along?

**Comment by JodiNA** [comment] 2016-02-18 16:04
Hi there @afawcett - Just came across the same issue with a new rollup in NPSP 3 while trying to delete opportunities.  Will work on getting this set for repro in a dev or this/next week.  

I tried changing the summary from realtime to scheduled, but that didn't make a difference.  I am only able to delete records with the summary inactive.

I'm getting the same error now as I got in my 8/18 post.  This is the summary causing the issue.  

(I've noted about validation rules in the description, but that's not what's causing the issue, as the opportunities I'm trying to delete are not affected by the rules.)

![summary](https://cloud.githubusercontent.com/assets/8515331/13149295/058f26b2-d62f-11e5-8c24-33f106bd2de1.jpg)

**Comment by afawcett** [comment] 2016-02-18 17:56
Excellent @JodiNA, this will be great, i'd love to have more support to work on issue around this more easily, i'm also still keen to leverage new custom metadata support to perhaps package a few common rollups so its as easy as installing an extension package to set them up. One step at a time though.... :+1:

**Comment by JodiNA** [comment] 2016-03-02 22:33
Great news!  I've got a dev. org up and running and getting the error!

What are the next steps?  What's the best way to get you into the dev. org? 

For repro:
1) Create an opportunity with close date anytime last year and amount!=NULL and Account=Test Account (it's the only account in there!).
2) Save.  Try to delete, and you'll get the error.

There's only one lookup summary, so it should be easy to spot!

**Comment by afawcett** [comment] 2016-03-05 08:19
@JodiNA thats great news indeed, could you perhaps create me a user? (DM me if you don't have my email). I'd like to designate this org to be used for all NPSP testing in the future, what do you think?

**Comment by JodiNA** [comment] 2016-03-07 18:52
Hi @afawcett, happy to make you a user.  I'm not actually sure how to send you a direct message through GitHub to get your email!  Could you advise?

And, yes, totally game for using this org for NPSP testing!  Have at it!  And, glad that I can be helpful in some way with DRLS developments.

**Comment by afawcett** [comment] 2016-03-09 18:48
I'm not sure either are you on Twitter?

**Comment by JodiNA** [comment] 2016-03-09 19:22
@afawcett I just sent you a message through the Success Community to your Financial Force account.

**Comment by afawcett** [comment] 2016-03-14 08:19
Excellent, i got it and i'm logged in! I'll now attempt to recreate the error, thanks so much for putting this org together, so many of the tools users are using it with NPSP, so this is a great resource.

**Comment by JodiNA** [comment] 2016-03-15 14:52
Awesome!  Have you been able to reproduce the error?

Glad this can be a resource for NPSP testing. :-)

**Comment by afawcett** [comment] 2016-03-20 10:58
Yes! :+1: 

I've got a full stack dump and looking into it now....

There were custom validation error(s) encountered while saving the affected record(s). The first validation error encountered was "Apex trigger dlrs_OpportunityTrigger caused an unexpected exception, contact your administrator: dlrs_OpportunityTrigger: execution of AfterDelete caused by: System.DmlException: Update failed. First exception on row 0 with id 006360000049l3xAAA; first error: ENTITY_IS_DELETED, entity is deleted: []: Class.dlrs.RollupService.Updater.updateRecords: line 1159, column 1".

**Comment by afawcett** [comment] 2016-03-20 13:55
Ok, i've made a fix for this, which should be in the release by the time you read this. It actually, ironically, had nothing to do with NPSP this one (though it think others might). So one question though, why are you doing this kind of self referencing lookup vs using like a formula field?

**Comment by afawcett** [comment] 2016-03-20 14:41
Fixed in v2.3.

**Comment by JodiNA** [comment] 2016-03-21 14:54
Great to hear this is fixed, @afawcett!  Or at least the part that was breaking from the rollup I set up!

I am going to go back and check about the original error I had, with NPSP 2.  I'm curious if it was the same self-referencing issue and I didn't realize it.

The reason I did a rollup calculation on the same record (what you said, self-referencing) is that I wanted to create a Rollup Summary field on Accounts.  It's not possible to use formula fields in Rollup Summaries, so this was how I did it.  So, essentially, my options were to do one formula field on opportunities and then potentially a bunch of Lookup Summaries based off of that field, or one self-referencing Lookup Summary and then I can take advantage of the native SF functionality and do multiple rollup summaries off of that.  I chose the latter. Does that make sense?

Another alternative would have been to do a workflow rule on the opportunity to update the field, but that doesn't quite work either because there isn't a good way to trigger revaluation of the records the way I can do with DLRS.

Hope that helps as an explanation!

**Comment by JodiNA** [comment] 2016-03-21 16:47
I'm going to try to set up the the rollup I was getting with Households in the developer org for repro and testing.

**Comment by JodiNA** [comment] 2016-03-21 18:07
Hi again!  I set up another rollup in the dev. org which mimics one of the issues I was having. The rollup is called "Household Member IDs."  The rollups concatenates the IDs of all contacts in a Household.  The error occurs when you try to delete a contact.

The caveat is that the contact must have a Household.  Because the account model is Households, a household will not be generated automatically.  To reproduce the error, I went and manually created a Household for Test Contact.

The error is the following: 

Validation Errors While Saving Record(s)
There were custom validation error(s) encountered while saving the affected record(s). The first validation error encountered was "Apex trigger dlrs_ContactTrigger caused an unexpected exception, contact your administrator: dlrs_ContactTrigger: execution of AfterDelete caused by: System.DmlException: Update failed. First exception on row 0 with id a0336000001uRGmAAM; first error: ENTITY_IS_DELETED, entity is deleted: []: (dlrs)".

**Comment by JodiNA** [comment] 2016-03-21 19:45
Hi again.  I was able to recreate the last weird NPSP error I was getting in one of my sandboxes that is still on NPSP 2 and using the One-to-One account model.  I tried to recreate in the dev org, but I wasn't able to get the problem to occur.  So, maybe it's a non-issue, but I figured I should document it anyhow.

But, these are the steps and problem:

1) Create a rollup summary that rolls up from the ghost account (one-to-one account) to the contact.  I did this in the dev. org copying the one I have in my Sandbox (also in image).  It's called "One-to-One IDs".
2) Create a contact.
Result: Upon saving the new contact, not one, but TWO Household records will have been created.  One will be connected to the contact via lookup, and the other will be unrelated (find in search).

To test in the dev. org, I change the Account Model to "One-to-One."  Then I selected under the Household setting Household Object Rules "All Individual Contacts."  These two settings ensure that a ghost account is created for each contact, and the field in the rollup will be populated.

Here is a screencast of the error happening in my sandbox. View of the rollup is attached.
http://www.screencast.com/t/oH9TdvFHk3
<img width="1050" alt="one-to-one_ids" src="https://cloud.githubusercontent.com/assets/8515331/13931875/c2dc2958-ef7b-11e5-904f-49f9fe670838.png">

**Comment by afawcett** [comment] 2016-03-22 21:02
Ok i've been trying to recreate your Contact delete issue first, can you reset the org and confirm the steps to reproduce this error and we can start with this one. 

Regarding your explanation on the self referencing rollup, it's probably me, but i'm not really getting it as yet. But lets focus on the Contact issue for the mo... :+1:

**Comment by afawcett** [comment] 2016-03-22 21:34
I have setup this a tag to group [NPSP](https://github.com/afawcett/declarative-lookup-rollup-summaries/labels/NPSP) related issues.  

So we can see if we can team up on what i think is a general issue. My personal challenge is i don't have any knowledge of NPSP.  @JodiNA over in issue https://github.com/afawcett/declarative-lookup-rollup-summaries/issues/39 has kindly worked with to setup a reproduction org with DLRS and NPSP installed within. 

This has already led to one issue being resolved in v2.3 lets see if we can close in on more. I'm happy to create users in this org so we can work to reproduce the issues in that org and i can debug more easily, just message me via SF Community or DM via Twitter your email and i'll setup a user.

**Comment by JodiNA** [comment] 2016-03-22 22:35
To reproduce the contact delete issue:

1) Ensure that the Lookup Summary "Household Member IDs" is active and is set to realtime calculations.
2) Create a new contact.
3) Create a new household (not household account, which will be created automatically upon contact creation)
4) Return to new contact.  Lookup new household from contact record.  The household name will have changed to "Anonymous Household" (this is due to something else.. .just ignore for now)
5) On HH record, confirm that Household Member ID field is populated (via rollup).
6) Attempt to delete contact.

Let me know if that doesn't work! 

I've left the NPSP account model to the newly recommended setting, which is why the household is not generated automatically.  If needed, I can change the settings.  But I thought it would be more useful to be using the model that more orgs are likely to be using.

**Comment by afawcett** [comment] 2016-03-22 23:36
Thanks! :+1:

**Comment by afawcett** [comment] 2016-03-25 10:35
Ok great, reproduced it! Now to dig in... :+1:

**Comment by JodiNA** [comment] 2016-03-25 14:52
Sweet!

On Friday, March 25, 2016, Andrew Fawcett <notifications@github.com
<javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:

> Ok great, reproduced it! Now to dig in... [image: :+1:]
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/afawcett/declarative-lookup-rollup-summaries/issues/39#issuecomment-201235727>
>


-- 
*Jodi Nemser-Abrahams*
Information & Data Manager
Keshet
284 Amory Street
Jamaica Plain, MA 02130
617.524.9227x111

Web: www.keshetonline.org
Facebook: www.facebook.com/KeshetGLBTJews
Twitter: @KeshetGLBTJews <https://twitter.com/KeshetGLBTJews>
Blog: www.myjewishlearning.com/category/keshet/

*Subscribe for LGBT* Jewish news, resources and inspiration in your inbox
<http://bit.ly/1E6oJYK>.

*Registration <http://www.keshetonline.org/teenshabbaton/> for our first
ever West Coast Shabbaton for LGBTQ and ally teens is open! *Find more
information *here* <http://www.keshetonline.org/teenshabbaton/>.

*Stand up for transgender rights.* Sign Keshet's petition
<https://www.keshetonline.org/work/petition-in-support-of-full-transgender-rights-in-massachusetts/support-transgender-rights-in-ma/>
calling
Massachusetts legislators to support “An Act Relative to Transgender
Anti-Discrimination."

A teen. A mom. A straight rabbi and a queer rabbi.
See how we are transforming the Jewish community together
<https://youtu.be/3b8NL5jwt4o>.

**Comment by afawcett** [comment] 2016-08-15 19:35
These [NPSP related issues](https://github.com/afawcett/declarative-lookup-rollup-summaries/labels/NPSP) have been open a while. Prior to an MVP event in Chicago this year, i did put out a shout out to get together with an NPSP dev to debug this further (my prior attempts failed since i cannot see the NPSP and lack the knowledge to set it up unmanaged). I did get some response from my Chatter post. The general view though was that these are NPSP v2 issues and that the use of NPSP v3 is recommended. So my questions are... do those on this issue agree re: NPSP v2? And if so should we try to reproduce these on NPSP v3 or is the issue even known to exist on NPSP v3?

**Comment by ashimasaigal** [comment] 2016-08-15 20:03
Andrew, I do believe this is an issue with NPSP V3, so I can help you with this. It seems you need an unmanaged package installation of the NPSP V3 in an Org. Let me know see if I can create one and add you as an Admin to that. Would that help? I can likely help debug as well, if that would be helpful. Let's chat, I want to help with this one.

**Comment by afawcett** [comment] 2016-08-15 20:05
Oh yes please, that will be great. Yes lets get a dev org up and running, deploy both unmanaged into it and attempt to reproduce. Happy to do a screenshare or whatever to collaborate. So yes please, if you create an org, deploy NPSP into it, create me an admin user and i'll push DLRS unmanaged into it, then pass it back to you to repo, hows that sound?

**Comment by ashimasaigal** [comment] 2016-08-15 20:11
I'm happy to do that Andrew. I'll work to get the dev org set up and you added. Should I use andy@andyinthecloud.com  as your email or another email address? I'll let you push the DLRS into the instance and then I'll play and create the issue, okay?

You're the best!

**Comment by afawcett** [comment] 2016-08-18 07:35
Yep that email is fine.

**Comment by wyan-carter** [comment] 2016-12-05 23:27
Hi Andrew,

I'm having this issue too unfortunately, and I'm on v3.85 of the NPSP, and 2.4.2 of the DLRS tool. The error I'm getting is when there is only one contact connected an NPSP household, and we attempt to change the account that the contact is connected to. It seems the NPSP is attempting to delete the old household at the same time that the DLRS is attempting to update it. We have a process workaround thankfully, so it's not urgent, but I thought it would be worth reporting. Let me know if you need any more info from me. Thanks Andrew.

Wyan

**Comment by wyan-carter** [comment] 2016-12-05 23:38
I should say that we do have a process workaround, but it's actually very tricky to fix issues. We have to either delete the contact and recreate, or create a dummy additional contact record in the household that then gets deleted when we manually delete the superfluous household record. Would be great to have a solution!

**Comment by afawcett** [comment] 2016-12-09 02:08
Thanks @wyan-carter always great to get more insights like this, appreciate this.

**Comment by afawcett** [comment] 2017-01-09 03:02
Thanks to everyone on this issue an others, i have now just applied a fix to v2.7 to address this issue. Basically making the tool tolerant of errors occurring when the parent record has been deleted by child trigger logic. As triggers fire in non-deterministic times, this bug has also been quite hard to pin down, as well as needing NPSP installed and configured in a way i can debug. Thank you all for your help! Fixed in v2.7!

**Closed by afawcett** 2017-01-09 03:02 UTC
Labels: bug, NPSP

**Comment by wyan-carter** [comment] 2017-01-11 03:14
Brilliant, thanks Andrew! Really appreciate your hardwork on making this tool better, we rely on it for so much. Thanks again.

**Comment by rahulshukla1910** [comment] 2021-03-03 13:04
Getting Thi Error While converting the lead and selecting the Account Type "HouseHold" how can we change the default record type.
Error: Insert failed. First exception on row 0; first error: CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY, npsp.TDTM_Address: execution of AfterInsert caused by: System.DmlException: Delete failed. First exception on row 0 with id a0K6s000000Phf8EAC; first error: ENTITY_IS_DELETED, entity is deleted: [] (npsp): []
*Record Owner
