### ISSUE TITLE
ERROR: dlrs_ContactTrigger: System.LimitException

### ISSUE THREAD

**Issue by RajdeepK** [afawcett/declarative-lookup-rollup-summaries#355] opened 2016-07-15 18:16 UTC
Hi,

I was trying to update mass update a custom field on Contact object using dataloader.io and it returned this error: ERROR: dlrs_ContactTrigger: System.LimitException. 
I tried using import wizard and got the same error.

Also I am getting random flowApplication errors which are not related to any actions taken and some API errors which Salesforce Support team said are caused by dlrs. Here are the errors:

**FlowApplication Error:**
An error occurred at element myDecision (FlowDecision).
The flow failed to access the value for myVariable_current.RecordType.DeveloperName because it hasn't been set or assigned.
This report lists the elements that the flow interview executed. The report is a beta feature.
We welcome your feedback on IdeaExchange.
Flow Details
Flow Name: Update_mailing_address_of_org_donor_proxy_contact
Type: Workflow
Version: 1
Status: Active
Flow Interview Details
Interview Label: Update_mailing_address_of_org_donor_proxy_contact-1_Account
Current User: Rajdeep Kaur (00516000006QYoI)
Start time: 13/07/2016 10:48 AM
Duration: 0 seconds
How the Interview Started
Rajdeep Kaur (00516000006QYoI) started the flow interview.
Some of this flow's variables were set when the interview started.
myVariable_old = 0011600001wVkVrAAK
myVariable_current = 0011600001wVkVrAAK
ASSIGNMENT: myVariable_waitStartTimeAssignment
{!myVariable_waitStartTimeVariable} Equals {!Flow.CurrentDateTime}
Result
{!myVariable_waitStartTimeVariable} = "13/07/2016 10:48 AM"
DECISION: isChangedDecision2_myRule_1_BillingCity
DECISION: isChangedDecision3_myRule_1_BillingCountry
DECISION: isChangedDecision4_myRule_1_BillingState
DECISION: isChangedDecision5_myRule_1_BillingStreet
DECISION: isChangedDecision6_myRule_1_BillingPostalCode

**API Error:**
Apex trigger cv.GiftAssetInsertUpdateTrigger caused an unexpected exception, contact your administrator: cv.GiftAssetInsertUpdateTrigger: execution of AfterInsert caused by: System.DmlException: Update failed. First exception on row 0 with id 0061600000pM6zKAAS; first error: UNKNOWN_EXCEPTION, The record couldn’t be saved because it failed to trigger a flow. A flow trigger failed to execute the flow with version ID 3011600000092sJ. Contact your administrator for help.: Class.cv.GiftAssetUtils.updateDonationAmount: line 54, column 1 

Do you know what could have caused these errors? Appreciate any help in resolving these.

Thanks
Rajdeep

**Comment by afawcett** [comment] 2016-07-15 19:57
The root cause of this problem is not the rollup tool i'm afraid. You have an issue in a Flow that has been deployed in your org. This is the error...

    The flow failed to access the value for myVariable_current.RecordType.DeveloperName because it hasn't been set or assigned.

The error is in this flow Update_mailing_address_of_org_donor_proxy_contact. It looks like its because the RecordType.DeveloperName has not been queried or passed into the Flow. How is the Flow being called?

Its hard to see what impact DLRS is having here, everything points to the Flow issue, i don't even see anything DLRS related in the log above. Did Salesforce say anything more specific as to why they think it is the DLRS code?

If you deactivate the DLRS rollup, de-select Activate, does it work?

**Comment by RajdeepK** [comment] 2016-07-18 14:57
Hi Andrew,

Thank you for your response.

The flow is being called by a process builder based workflow. I am already
in contact with Salesforce support because of the other issues we are
having due to that Flow. It could be the root cause of all the issues.
I'll try to deactivate the DLRS rollup once Salesforce guys narrow the
issue down a bit further.

Thanks for looking into this. I'll get back to you with more information if
fixing the flow doesn't resolve the issue.

Thanks,
Rajdeep








Thanks!
Rajdeep

**Comment by afawcett** [comment] 2016-08-15 19:45
I'll close this issue out for now, however you can still add comments and if needed we can re-open. Thanks. 👍

**Closed by afawcett** 2016-08-15 19:45 UTC
Labels: discussion
