### ISSUE TITLE
null pointer exception in RollupService class

### ISSUE THREAD

**Issue by kushkella** [afawcett/declarative-lookup-rollup-summaries#363] opened 2016-08-01 19:30 UTC
I've some code in place that merges two accounts on some conditions. And I've some roll-ups on account that should work when two accounts are merged, but I'm getting this error:

```
Class.dlrs.RollupService.updateMasterRollupsTrigger: line 938, column 1
Class.dlrs.RollupService.handleRollups: line 842, column 1
Class.dlrs.RollupService.triggerHandler: line 307, column 1
Trigger.dlrs_AccountTrigger: line 7, column 1
12:20:09.191 (4043977430)|FATAL_ERROR|System.NullPointerException: Attempt to de-reference a null object
```

I can see where it can cause a null pointer exception in the codebase, but I don't understand why it would do so. Would really appreciate some help.

**Comment by kushkella** [comment] 2016-08-02 22:56
It seems like this error always comes up if there is a merge trigger installed for that particular object.

**Comment by findrohitsingh** [comment] 2016-08-03 05:17
Yes, I am also having the same problem. When I am trying to merge account, I am getting error:

`Apex trigger dlrs_AccountTrigger caused an unexpected exception, contact your administrator: dlrs_AccountTrigger: execution of AfterDelete caused by: System.NullPointerException: Attempt to de-reference a null object: Class.dlrs.RollupService.updateMasterRollupsTrigger: line 938, column 1`

I am not able to figure out this. I would appreciate if you could help me.

**Comment by kushkella** [comment] 2016-08-03 05:25
I removed the parent object trigger as an interim fix, changed the Calculation Mode to Developer and added a scheduled job that updates that particular roll-up nightly. I've yet to find a fix that would prevent this from happening. Will keep everyone posted as I dig deeper. Thanks!

**Comment by findrohitsingh** [comment] 2016-08-03 07:28
Hi,
Thank you for your prompt response.
I have one question. Can we schedule it for every 5 mins so record will
refresh after 5 min instead of night schedule?

Regards
Rohit Singh

**Comment by JimBTek** [comment] 2016-08-03 14:53
have you looked through all the docs including this page about code coverage issues?  https://github.com/afawcett/declarative-lookup-rollup-summaries/wiki/Challenges-with-Code-Coverage

DLRS automatically creates a very basic trigger and it can interfere with other triggers if you have them so  you will need to modify the trigger it generates to play well with your code.  Alternatively like you are doing you can remove the trigger if you are not doing realtime calculations.

@findrohitsingh you should be able to change the cron schedule to recalculate very often (i have some that recalculate on the hour)  but consider performance and how much data you will be calculating.

**Comment by kushkella** [comment] 2016-08-03 17:02
I don't think it is a code coverage issue. The trigger is definitely not working even with the standard merge operation. The code I've doesn't do anything special, but if I add a trigger it breaks my existing test. And when deploying the trigger, it never shows those failures because it doesn't run my full test suite. I think it would be a cool option to have to prevent breaking our code base. But more importantly, I think something goes wrong when doing a merge operation when you've a trigger for parent object in place (required for real-time and scheduled calculations).

**Comment by afawcett** [comment] 2016-08-03 18:33
Are you using Custom Metadata based rollups?

**Comment by kushkella** [comment] 2016-08-03 21:02
Yes, I'm using Custom Metadata based roll-ups and I'm on the latest version of the app.

**Comment by findrohitsingh** [comment] 2016-08-04 02:24
Yes Andy.

**Comment by daveerickson** [comment] 2016-08-04 13:56
I am also having this issue that shows up with Metadata rules while merging Contacts. A temporary fix seems to be deleting the ghost metadata rules, then the merge happens fine and all the rules are recreated.

Another issue is that my users only have the Process Rollups permission set, so if they run a process that try's to create the ghost records they get a failure. Im using apex enterprise patterns throughout my org and running in Developer mode for my rollups. Maybe I need to move the dlrs.RollupService.rollup method from an inner class without sharing?

**Comment by afawcett** [comment] 2016-08-05 21:06
Marking this as a priority fix

**Comment by afawcett** [comment] 2016-08-14 08:22
This is a duplicate of this https://github.com/afawcett/declarative-lookup-rollup-summaries/issues/371. I have also fixed permission set issue in this https://github.com/afawcett/declarative-lookup-rollup-summaries/issues/345

**Closed by afawcett** 2016-08-14 08:22 UTC
Labels: bug, priority
