### ISSUE TITLE
Salesforce Standard Order object OpportunityID field not recognized

### ISSUE THREAD

**Issue by JeffMTI** [afawcett/declarative-lookup-rollup-summaries#98] opened 2014-12-05 12:41 UTC
Trying to define a rollup from Order onto Opportunity using the standard Lookup(Opp) field gets Field does not exist on OpportunityId.

**Comment by afawcett** [comment] 2015-02-07 23:33
Fixed in v1.17.

![screen shot 2015-02-07 at 23 35 51](https://cloud.githubusercontent.com/assets/1167760/6094430/bd96c066-af21-11e4-8a14-3e1ea5ecaed5.png)

**Closed by afawcett** 2015-02-07 23:33 UTC
Labels: bug

**Comment by karenhite** [comment] 2017-03-22 13:39
@afawcett I was not able to do this from my org. I tried to place OpportunityId as the relationship field and it did not exist still. Could you please guide me with the steps on how to make it work? I'm trying to create a roll up summary for the field Next Activity Date that will be allocated within the Opportunity object (Parent) and the Child Object  is Task.

**Comment by DanDonin** [comment] 2017-03-22 13:46
On task I think you want WhatId

**Comment by karenhite** [comment] 2017-03-22 13:59
![screenshot 2017-03-22 07 59 17](https://cloud.githubusercontent.com/assets/26600847/24201378/7cef3f32-0ed5-11e7-8bdf-944e86be3d9c.png)

Is this what you are saying?

**Comment by DanDonin** [comment] 2017-03-22 14:00
Yup

**Comment by karenhite** [comment] 2017-03-22 14:02
Did not seemed to work. I have 2 Open activities and the Next Activity Date field is not getting filled out.
![screenshot 2017-03-22 08 01 29](https://cloud.githubusercontent.com/assets/26600847/24201502/d4323970-0ed5-11e7-96de-e77c83536552.png)

**Comment by DanDonin** [comment] 2017-03-22 14:02
Use calculate or edit one of them. Dlrs needs edit or create or update
calls to trigger.

**Comment by karenhite** [comment] 2017-03-22 14:07
Tried to do that and still the field is not being updated. Also, when the rollup summary is active, I'm not able to edit or create any tasks.

**Comment by DanDonin** [comment] 2017-03-22 14:09
Is the dlrs active? Have you deployed the trigger? What error do you get
when trying to create a task?

On Mar 22, 2017 7:07 AM, "karenhite" <notifications@github.com> wrote:

Tried to do that and still the field is not being updated. Also, when the
rollup summary is active, I'm not able to edit or create any tasks.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/afawcett/declarative-lookup-rollup-summaries/issues/98#issuecomment-288409012>,
or mute the thread

**Comment by karenhite** [comment] 2017-03-22 14:11
![screenshot 2017-03-22 08 10 00](https://cloud.githubusercontent.com/assets/26600847/24201871/035d3e60-0ed7-11e7-9316-fe878b7f826a.png)
It is active and the trigger has been deployed. This is the error:

**Comment by DanDonin** [comment] 2017-03-22 14:13
You'll want to use the Last or First function when doing rollups on
date/time fields.

**Comment by karenhite** [comment] 2017-03-22 14:19
I'd like to see the min of open activities. Will First allow me to do so?

**Comment by DanDonin** [comment] 2017-03-22 14:20
The min so the oldest one?

**Comment by karenhite** [comment] 2017-03-22 14:22
The closest of all of the open activities. If I have 3 dates:
1. March 22nd
2. March 30th 
3. April 1st
I'd like to see March 22nd as the next activity date

**Comment by DanDonin** [comment] 2017-03-22 14:25
The closest to what? To today's date?

**Comment by karenhite** [comment] 2017-03-22 14:31
Yes, even if it's in the past (overdue)

**Comment by DanDonin** [comment] 2017-03-22 14:34
I forget how dlrs sorts records I think it is ascending so i think you'll
wanna use the first operator.

**Comment by karenhite** [comment] 2017-03-22 15:04
:( I tried to do it with First but now it gives me an error: Error:Master and detail fields must be the same field type (or text/Id based) for First or Last operations

I checked both fields (ActivityDate) and Next Activity Date and they are both Date/Time fields.

**Comment by DanDonin** [comment] 2017-03-22 15:07
Activity date is a date not a date/time.

**Comment by karenhite** [comment] 2017-03-22 16:13
Awesome. Ok so I was able to fix this and it is showing a date BUT it's showing the first activity date. I want it to be the first activity date of Open Activities not All Activities. How can I filter this?

**Comment by DanDonin** [comment] 2017-03-22 16:21
Set in the relationship criteria isClosed=false

**Comment by karenhite** [comment] 2017-03-22 17:02
It worked! Thank you so much!

**Comment by karenhite** [comment] 2017-03-22 17:07
Now my only concern is that this trigger is affecting another workflow. I got this error below. 
How can I make sure to not affect the workflow? 

FlowApplication <info@salesforce.com>
10:50 AM (16 minutes ago)

to me 

Add to Salesforce Tracking Follow-up
Error element myRule_1_A1 (FlowRecordCreate).
This error occurred when the flow tried to create records: CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY: dlrs_TaskTrigger: execution of AfterInsert caused by: System.DmlException: Update failed. First exception on row 0 with id 0065000000fOQlLAAW; first error: FIELD_CUSTOM_VALIDATION_EXCEPTION, You cannot update Closed Won Opportunities, please contact your System Administrator if an update needs to be made.: [] (dlrs) . For details, see API Exceptions.
This report lists the elements that the flow interview executed. The report is a beta feature.
We welcome your feedback on IdeaExchange.
Flow Details
Flow Name: Closed_Won_Opportunity_Process
Type: Workflow
Version: 13
Status: Active
Flow Interview Details
Interview Label: Closed_Won_Opportunity_Process-13_InterviewLabel
Current User: Tony Diaz (0055000000679jU)
Start time: 3/22/2017 9:50 AM
Duration: 0 seconds
How the Interview Started
Tony Diaz (0055000000679jU) started the flow interview.
Some of this flow's variables were set when the interview started.
myVariable_old = 0065000000fOQlLAAW
myVariable_current = 0065000000fOQlLAAW
ASSIGNMENT: myVariable_waitStartTimeAssignment
{!myVariable_waitStartTimeVariable} Equals {!Flow.CurrentDateTime}
Result
{!myVariable_waitStartTimeVariable} = "3/22/2017 9:50 AM"
DECISION: myDecision
Executed this outcome: myRule_1
Outcome conditions: 1 AND (2 OR 3 OR 4 OR 5)
1. {!myVariable_current.StageName} (Closed Won) Equals Closed Won
2. {!myVariable_current.Lead_Channel__c} (Telemarketing) Does not equal Internal
3. {!myVariable_current.LeadSource} (Telemarketing) Does not equal Cross Sell
4. {!myVariable_current.LeadSource} (Telemarketing) Does not equal Up-sell
5. {!myVariable_current.LeadSource} (Telemarketing) Does not equal Win-back
Logic: Advanced Logic (1 AND (2 OR 3 OR 4 OR 5))
DECISION: myRule_1_pmetdec
RECORD CREATE: myRule_1_A1
Create one Task record where:
ActivityDate = {!formula_6_myRule_1_A1_ActivityDate} (March 22, 2017)
Description = Send the Welcome Email to the appropriate individual as this Opportunity is Closed Won.
OwnerId = {!myVariable_current.OwnerId} (0055000000679jUAAQ)
Status = Open
Subject = Send Welcome Email
WhatId = {!myVariable_current.Id} (0065000000fOQlLAAW)
Result
Failed to create record.
Error Occurred: This error occurred when the flow tried to create records: CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY: dlrs_TaskTrigger: execution of AfterInsert caused by: System.DmlException: Update failed. First exception on row 0 with id 0065000000fOQlLAAW; first error: FIELD_CUSTOM_VALIDATION_EXCEPTION, You cannot update Closed Won Opportunities, please contact your System Administrator if an update needs to be made.: [] (dlrs) . For details, see API Exceptions.
Salesforce Error ID: 1687453295-63410 (-736724398)

**Comment by DanDonin** [comment] 2017-03-22 17:12
This is a process builder that you have that is failing.  You can bring a formula down to the task that shows if an opp is closed and exclude dlrs where the opp is closed, or you can set up your flow to not fire when that dlrs field is being updated.

**Comment by karenhite** [comment] 2017-03-22 17:46
Ok so I have the following things that are affecting:

- Validation Rule in the Opportunity Object that does not allow users to edit Closed Won Opps: 
AND( 
ISPICKVAL(PRIORVALUE(StageName),"Closed Won"), 
NOT(OR( 
$Profile.Id = "00e50000001A5gA", 
$Profile.Id = "00e50000001QOJf")) 
)&& 
NOT(ISCHANGED( Next_Scheduled_Activity_Date__c ))&& 
NOT(ISCHANGED( Client_Questionnaire_Link__c ))
- Process Builder in the Opportunity Object that creates different tasks for users when an opportunity is placed as Closed Won

How would I be able to make the exemption so this error is not applicable?

**Comment by DanDonin** [comment] 2017-03-22 17:50
What causes the flow to fire?

**Comment by karenhite** [comment] 2017-03-22 17:57
The Stage to be marked as Closed Won

**Comment by DanDonin** [comment] 2017-03-22 18:02
Does it fire on every edit? Under Advanced on the Criteria in PB select the Do you want to execute the actions only when specified changes are made to the record?  This will prevent it from running every time the record is edited and only when the record used to not meet the criteria and now does meet the criteria.

**Comment by karenhite** [comment] 2017-03-22 19:22
This was checked already. When we got the error it was the first time the opportunity was being placed with Stage= Closed Won.

**Comment by karenhite** [comment] 2017-03-22 19:38
I was reading about the Process Builder Calculation Mode. Would it help  to include this action in the PB that is giving me an error?

**Comment by DanDonin** [comment] 2017-03-22 20:01
Not really, you are running into order of operations errors. PB is trying to make an update, and when PB makes that update it creates a Task, that triggers DLRS, that then runs into an error due to the validation rule of not able to update the opp.  Need to figure out a way to let DLRS around the validation rule.

**Comment by karenhite** [comment] 2017-03-22 20:08
Opportunity Validation Rule: Cannot Edit Closed Won OppsxAND(
ISPICKVAL(PRIORVALUE(StageName),"Closed Won"),
I Just changed the VR to this and moved the DLRS to Real Time to see if it allows me to.
NOT(OR(
$Profile.Id = "00e50000001A5gA", 
$Profile.Id = "00e50000001QOJf"))
)&&
NOT(ISCHANGED( Next_Scheduled_Activity_Date__c ))&&
NOT(ISCHANGED( Client_Questionnaire_Link__c )&&NOT(ISCHANGED(NEXT))

**Comment by karenhite** [comment] 2017-03-22 20:16
Tried to test it without luck. The error appeared again.

**Comment by DanDonin** [comment] 2017-03-22 20:17
Try turning off the VR 100% and see if the error still happens.

**Comment by karenhite** [comment] 2017-03-22 20:53
Once the VR was deactivated, everything is running smooth.

**Comment by DanDonin** [comment] 2017-03-22 21:28
Yeah so the issue if trying to find a way to systematically have the VR allow DLRS to do its thing.  The problem is DLRS will run as whatever user triggers it.

**Comment by antoniobarrosjr** [comment] 2017-04-18 22:08
Hello, I´m facing this same problem and I was not able to find the solution. the case seems to be closed. Can someone help ?

Thanks,
