### ISSUE TITLE
first error: CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY,   dlrs_ContactTrigger: execution of AfterUpdate  caused by: System.NoAccessException: Entity is not api accessible

### ISSUE THREAD

**Issue by jasonkelly** [afawcett/declarative-lookup-rollup-summaries#426] opened 2016-11-04 20:43 UTC
Error Type: Batch Apex error
Error Date: 2016-11-04 03:10:08
Message: "First error: Update failed. First exception on row 0 with id 003A000000uVn8nIAC; first error: CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY, dlrs_ContactTrigger: execution of AfterUpdate caused by: System.NoAccessException: Entity is not api accessible Class...."

Context: npsp__RLLP_OppContactRollup_BATCH

Stack Trace:
 null

----------

The above error started appearing this week, despite releasing no new Apex code recently.

What is the best way to debug and fix the error? We are running the latest versions of both Declarative Lookup Rollup Summaries Tool and the Nonprofit Success Pack.

**Comment by graham228221** [comment] 2016-11-06 19:56
We've been getting the same thing, it seems to have started when the Nonprofit Success Pack was updated on 2nd November, we've had this error message every night since then. I've been receiving it from two different orgs where we are using both DLRS and NPSP.

npsp__RLLP_OppContactRollup_BATCH is an Apex Class scheduled to run each night, and I also seem to always get an error for npsp__RLLP_OppSoftCreditRollup_BATCH.

I can see from release notes that they've changed how the error messages are generated, but I'm not much of an expert so not really sure what I'm looking for! https://github.com/SalesforceFoundation/Cumulus/releases

If there's anything I can help with to fix please let me know!

**Comment by cdcarter** [comment] 2016-11-07 18:03
Hey Folks,

Have you followed the instructions to change the scheduled jobs user in the NPSP? Located here: https://powerofus.force.com/articles/Resource/NPSP-Edit-or-Reschedule-NPSP-Scheduled-Jobs. There are some issues with the NPSP shadow user, so switching to an administrator account is required.

**Comment by graham228221** [comment] 2016-11-07 18:11
Yes spotted that earlier! And it seems to have solved the issue completely. Thanks.

**Comment by StephanieKing** [comment] 2016-11-16 21:27
I've been having this issue with some of my NPSP orgs, but I don't see what I am supposed to do with the above mentioned link? All of the users in my scheduled jobs are "Active", and I'm not wanting to change the scheduled time of any of my jobs.... I just want to stop the errors :-) What am I missing??

**Comment by afawcett** [comment] 2016-12-05 01:00
@StephanieKing if you've tried @cdcarter's issue then i suspect it's something described in this [issue](https://github.com/afawcett/declarative-lookup-rollup-summaries/issues/360). What org edition are you running?

**Comment by StephanieKing** [comment] 2016-12-05 15:06
Yes, this issue doesn't seem to help me, I'll check #360 , thanks!

**Comment by afawcett** [comment] 2017-01-01 03:54
Closing this, as its a duplicate of another issue. Look for updates on https://github.com/afawcett/declarative-lookup-rollup-summaries/issues/360.

**Closed by afawcett** 2017-01-01 03:54 UTC
Labels: bug, duplicate, priority
