### ISSUE TITLE
BulkAPI conflicts in realtime

### ISSUE THREAD

**Issue by ScottBAS** [afawcett/declarative-lookup-rollup-summaries#450] opened 2017-01-23 20:00 UTC
I love this tool. So happy I came across this. Thank you for making this available to the masses!

Unfortunately, there is conflict with the BulkAPI process we have set up with our proprietary software. In short, the BulkAPI upserts Contact, Order__c and Order_Item__C (past 30 days).  

**Steps taken:**
- BulkAPI upserts Contact, Order__c and Order_Item__C (past 30 days).
- Created revenue DLRS "sum" roll-ups between Order_Item__c/Order__c, Order__c/Contact, and Order__c/Acccount
- Deployed Apex
- Scheduled for "Real-Time"

**Issue**
- During BulkAPI job import of Order__c, the following error occurs quite often. On 1/16/2017, 29,717 of 80,856 records failed to process. Error message: "dlrs_OrderTrigger: execution of AfterUpdate\n\ncaused by: System.DmlException: Upsert failed. First exception on row 24; first error: UNABLE_TO_LOCK_ROW, unable to obtain exclusive access to this record or 1 records: a0l60000006enLvAAI: []\n\nClass.dlrs.RollupService.updateMasterRollupsTrigger: line 946, column 1\nClass.dlrs.RollupService.handleRollups: line 815, column 1\nClass.dlrs.RollupService.triggerHandler: line 307, column 1\nTrigger.dlrs_OrderTrigger: line 7, column 1"

**Notes/Questions**

- I would like to utilize Real-Time so that there is not a question about data accuracy (IE are all roll-ups completed?).  
- I am thinking this is related to the deployed triggers' use of "before" methods, IE 'Before Insert", "Before Update", etc
- I removed the "before" methods in the triggers in Developer, but I could not successfully deploy the re-written triggers to Production. I am new to triggers, but I've got high hopes :/

**Comment by afawcett** [comment] 2017-02-18 22:47
Yes this problem occurs due to concurrency when the Bulk API runs multiple child inserts in parallel. The platform holds a lock on the parent record and sometimes there are collisions. This is actually by design on the platform side to avoid problems with data accuracy. Solving it is not easy. 

- Sometimes its best to just switch to one of the Schedule modes (see [wiki](https://github.com/afawcett/declarative-lookup-rollup-summaries/wiki/What-you-need-to-know-about-Scheduling-Rollups)). 
- Or disable the rollups during the import (set the Active field to false), do the upload then run a Calculate (via button or API call) then activate again (set Active field to true). 
- Other option, which is less performance, is to look for a Parallel setting in whatever tool your using to disable the use of parallel. This will help, but will make the job take longer. 

Hopefully this helps with a few things. Changing the triggers i am afriad will not help, it is the locking of the parent records to update the rollups that causes it.

**Comment by afawcett** [comment] 2017-02-18 22:51
I also just raised this enhancement request based on option 2 above. https://github.com/afawcett/declarative-lookup-rollup-summaries/issues/468

**Comment by afawcett** [comment] 2017-05-27 23:57
Closing since i have now raised this on an enhancement issue above.

**Closed by afawcett** 2017-05-27 23:57 UTC
Labels: discussion
