### ISSUE TITLE
I am trying to copy a reference into the parent record of the child who's date is the latest in the children

### ISSUE THREAD

**Issue by guygardner** [afawcett/declarative-lookup-rollup-summaries#124] opened 2015-02-21 00:25 UTC
I get this error when trying to save a new rollup summary:
    Master and detail fields must be the same field type (or text based) for First or Last operations

Schema:
   Account is the parent object
   Financing Round is the custom child object related to Account

Values I am trying to save:
  Lookup Relationship section
      Parent Object: Account
      Chid Object: Financing_Round__c
      Relationship Field: Account__c
  Rollup Details section
      Field to Aggregate: ID
      Field to Order by: Funding_Opened__c (date DT)
      Aggregate Operation: Last
      Aggregate Result Field: Latest_Financing_Round__c
      Active: (unchecked)
      Calculation Mode: Realtime

Any ideas how to do this without errors? Do I have something wrong?

The general idea is to expose the latest financing round record in Account Views, Searches and while viewing Account records so a user can quickly click on that link to go directly to the latest round record.

Thanks in advance for your help on this.
Guy

**Comment by afawcett** [comment] 2015-02-23 17:24
I think this is a bug, sorry, i'll take a look.

**Comment by afawcett** [comment] 2015-02-23 17:26
Duplicate of issue [121](https://github.com/afawcett/declarative-lookup-rollup-summaries/issues/121).

**Closed by afawcett** 2015-02-23 17:26 UTC
