### ISSUE TITLE
Trying to count # of events and tasks an owner has completed; OwnerId relationship field is failing

### ISSUE THREAD

**Issue by rwerner88** [afawcett/declarative-lookup-rollup-summaries#140] opened 2015-03-24 13:28 UTC
We are trying to count the monthly number of completed tasks and events for each sales rep. Right now we have 4 lookup roll-up summaries running to calculate these numbers. For each of these, the parent field is always User and the child is either Task or Event depending on which it is counting.

When I calculate these rollups manually there are no issues; however when scheduled to run at night with the other rollups in our org the jobs fail. The OwnerId relationship field seems to be the issue and for many of the jobs it is trying to use a Contact, Lead, or Account as the OwnerId along with the User. The Apex jobs lists the error as "First error: Invalid Id for User". In the lookup logs there are a ton of errors listed for all the Accounts, Contacts, and Leads the rollup tried to use as the parent object. Here is an image of one of our rollups so you can see how we set it up:

![lookup_error](https://cloud.githubusercontent.com/assets/11630877/6802539/7af88478-d1ff-11e4-96e8-7f65aeee8a36.jpg)

Any ideas on what's going on? Thanks!

**Comment by afawcett** [comment] 2015-03-26 08:28
Yes i've been seeing these type of errors come through from time to time as the platform emails me unhandled exceptions. I've had a few looks through the code to reverse engineer what might be the issue without success. So don't take this the wrong way, but i'm really pleased you seemed to have reproduced the issue and contact me! :+1: 

Next up is how to reproduce it in my environment! Its good that you seem to be using all standard objects, so i should be able to setup the rollups as you have done. I do wonder if there is some data sensitive element to it though, but lets see. So next step, can you give me a screenshot of all 4 rollup summaries please?

**Comment by afawcett** [comment] 2015-03-26 08:29
Oh and also can you share some examples of the errors in the lookup logs as well please.

**Comment by rwerner88** [comment] 2015-03-26 14:03
Here are the 4 rollups (one of them is on "developer" mode as we were experimenting with it, but they all are normally ran as scheduled):

![1](https://cloud.githubusercontent.com/assets/11630877/6847679/5dd8d044-d396-11e4-9777-fa47609d12c3.jpg)

![2](https://cloud.githubusercontent.com/assets/11630877/6847682/64cc7158-d396-11e4-8a42-7cf7a2391ef4.jpg)

![3](https://cloud.githubusercontent.com/assets/11630877/6847684/66f4fe82-d396-11e4-992c-5bcccce5650b.jpg)

![4](https://cloud.githubusercontent.com/assets/11630877/6847685/692fa38c-d396-11e4-994c-76b8371c391c.jpg)


In the logs there are a bunch of error logs, however they are all identical:

![log1](https://cloud.githubusercontent.com/assets/11630877/6847696/7abbcebe-d396-11e4-8de0-7459c5144569.jpg)

All of the logs are for the Account object as the parent. Under the apex jobs list the error shows "First error: Invalid Id for User"

**Comment by afawcett** [comment] 2015-06-08 21:13
I'm getting a sense of whats causing this now, i think it has to do with the OwnerId being able to point to different types of objects, not sure if this is possible for Event to have different parents though. Also i think another possible bug is the parent object may have been changed on the rollup, yet scheduled item records might still exist in the system for when the rollup records may have pointed to different parent objects. Are you able to clear the schedule item records from the system and see if you get this error again?

**Comment by afawcett** [comment] 2015-07-06 07:48
This is a duplicate of this [issue 185](https://github.com/afawcett/declarative-lookup-rollup-summaries/issues/185). Which is now fixed in the GitHub master branch and will be packaged shortly.

**Closed by afawcett** 2015-07-06 07:48 UTC
Labels: duplicate
